<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="ru" xml:lang="ru"><head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<meta charset="utf-8">
<meta name="generator" content="quarto-1.10.18">
<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">
<title>5&nbsp; Большие данные корпоративной отчётности – Количественные финансы</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: 1.5em;}
div.column{flex: auto;}
@media screen {
div.columns{gap: min(4vw, 1.5em);}
div.column{overflow-x: auto;}
}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>

<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./06-industry-analysis.html" rel="next">
<link href="./04-returns-risk.html" rel="prev">
<script src="site_libs/quarto-html/quarto.js" type="module"></script>
<script src="site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-116a87f4909111ce87c16683344de049.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-text-highlighting-styles">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-dark-0b552e407b994c949c80d38323c6ecd4.css" rel="stylesheet" class="quarto-color-scheme quarto-color-alternate" id="quarto-text-highlighting-styles">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-116a87f4909111ce87c16683344de049.css" rel="stylesheet" class="quarto-color-scheme-extra" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap-0c05c57a3ac6ecce481b1d5dedff5f54.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme" id="quarto-bootstrap" data-mode="light">
<link href="site_libs/bootstrap/bootstrap-dark-40a39973876dc97ad54823b52a24ffce.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme quarto-color-alternate" id="quarto-bootstrap" data-mode="light">
<link href="site_libs/bootstrap/bootstrap-0c05c57a3ac6ecce481b1d5dedff5f54.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme-extra" id="quarto-bootstrap" data-mode="light"><script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "Поиск не дал результатов",
    "search-matching-documents-text": "Результаты поиска",
    "search-copy-link-title": "Скопировать ссылку",
    "search-hide-matches-text": "Скрыть дополнительные результаты",
    "search-more-match-text": "дополнительный результат в этом документе",
    "search-more-matches-text": "дополнительных результата(-ов) в этом документе",
    "search-clear-button-title": "Очистить",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Отменить",
    "search-submit-button-title": "Найти",
    "search-label": "Поиск"
  }
}</script><style>html{ scroll-behavior: smooth; }</style>
<!--
  Настройки MathJax 4: шрифт STIX Two в тон основному тексту.
  Сам MathJax 4 подключается через html-math-method в _quarto.yml
  (Quarto 1.10 по умолчанию берёт MathJax 3, где этого шрифта нет).
--><script>
  window.MathJax = {
    output: {
      font: 'mathjax-stix2',
      displayOverflow: 'scroll'
    }
  };
</script>
</head>
<body class="nav-sidebar floating slimcontent quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top"><nav class="quarto-secondary-nav"><div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Переключить боковую панель навигации" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./05-accounting-data.html">Корпоративная отчётность</a></li><li class="breadcrumb-item"><a href="./05-accounting-data.html"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Большие данные корпоративной отчётности</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Переключить боковую панель навигации" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Поиск" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav></header><!-- content --><div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto"><div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./">Количественные финансы</a> 
        <div class="sidebar-tools-main">
    <a href="./quant-finance-book.pdf" title="Скачать PDF" class="quarto-navigation-tool px-1" aria-label="Скачать PDF"><i class="bi bi-file-earmark-pdf"></i></a>
    <a href="https://github.com/quantviews/quant-finance-book" title="Исходный код" class="quarto-navigation-tool px-1" aria-label="Исходный код"><i class="bi bi-github"></i></a>
</div>
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Поиск"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Предисловие</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./01-intro.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Введение</span></span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true">
 <span class="menu-text">Данные и инструменты</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true" aria-label="Переключить раздел">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./02-data-sources.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Источники финансовых данных</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./03-data-preparation.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Подготовка данных</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./04-returns-risk.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Доходность и риск</span></span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true">
 <span class="menu-text">Корпоративная отчётность</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true" aria-label="Переключить раздел">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./05-accounting-data.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Большие данные корпоративной отчётности</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./06-industry-analysis.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Отраслевой анализ</span></span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="true">
 <span class="menu-text">Временные ряды</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="true" aria-label="Переключить раздел">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-3" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./07-arma.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Свойства финансовых рядов и модели ARMA</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./08-volatility.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Волатильность: модели ARCH и GARCH</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./09-ml-forecasting.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Прогнозирование и машинное обучение</span></span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="true">
 <span class="menu-text">Риск и портфели</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="true" aria-label="Переключить раздел">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-4" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./10-var-es.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">VaR и Expected Shortfall</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./11-portfolio.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Портфельная теория</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./12-capm-factors.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">CAPM и факторные модели</span></span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" role="navigation" aria-expanded="true">
 <span class="menu-text">Долговой рынок</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" role="navigation" aria-expanded="true" aria-label="Переключить раздел">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-5" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./13-bonds.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">13</span>&nbsp; <span class="chapter-title">Облигации</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./14-credit-risk.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">14</span>&nbsp; <span class="chapter-title">Кредитный риск</span></span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-6" role="navigation" aria-expanded="true">
 <span class="menu-text">Торговые стратегии</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-6" role="navigation" aria-expanded="true" aria-label="Переключить раздел">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-6" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./15-backtesting.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">15</span>&nbsp; <span class="chapter-title">Бэктестинг и переобучение</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./16-momentum.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">16</span>&nbsp; <span class="chapter-title">Моментум и управление волатильностью</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./17-microstructure.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">17</span>&nbsp; <span class="chapter-title">Микроструктура рынка и как её измеряют</span></span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./references.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Литература</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-7" role="navigation" aria-expanded="true">
 <span class="menu-text">Приложения</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-7" role="navigation" aria-expanded="true" aria-label="Переключить раздел">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-7" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./appendix-python.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">A</span>&nbsp; <span class="chapter-title">Основы Python для финансиста</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./appendix-data.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">B</span>&nbsp; <span class="chapter-title">Справочник по данным</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./appendix-projects.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">C</span>&nbsp; <span class="chapter-title">Проекты, экзамен и оценивание</span></span></a>
  </div>
</li>
      </ul>
</li>
    </ul>
</div>
</nav><div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active"><h2 id="toc-title">Содержание</h2>
   
  <ul>
<li><a href="#sec-rfsd-source" id="toc-sec-rfsd-source" class="nav-link active" data-scroll-target="#sec-rfsd-source"><span class="header-section-number">5.1</span> Откуда берётся отчётность</a></li>
  <li><a href="#sec-forms" id="toc-sec-forms" class="nav-link" data-scroll-target="#sec-forms"><span class="header-section-number">5.2</span> Формы отчётности</a></li>
  <li><a href="#sec-polars" id="toc-sec-polars" class="nav-link" data-scroll-target="#sec-polars"><span class="header-section-number">5.3</span> Большие таблицы: Polars</a></li>
  <li><a href="#sec-okved" id="toc-sec-okved" class="nav-link" data-scroll-target="#sec-okved"><span class="header-section-number">5.4</span> Классификатор ОКВЭД</a></li>
  <li>
<a href="#sec-rfsd-quality" id="toc-sec-rfsd-quality" class="nav-link" data-scroll-target="#sec-rfsd-quality"><span class="header-section-number">5.5</span> Качество данных</a>
  <ul class="collapse">
<li><a href="#%D1%81%D1%85%D0%BE%D0%B4%D0%B8%D1%82%D1%81%D1%8F-%D0%BB%D0%B8-%D0%B1%D0%B0%D0%BB%D0%B0%D0%BD%D1%81" id="toc-сходится-ли-баланс" class="nav-link" data-scroll-target="#%D1%81%D1%85%D0%BE%D0%B4%D0%B8%D1%82%D1%81%D1%8F-%D0%BB%D0%B8-%D0%B1%D0%B0%D0%BB%D0%B0%D0%BD%D1%81"><span class="header-section-number">5.5.1</span> Сходится ли баланс</a></li>
  <li><a href="#%D1%81%D0%BA%D1%80%D1%8B%D1%82%D0%B0%D1%8F-%D0%BE%D1%82%D1%87%D1%91%D1%82%D0%BD%D0%BE%D1%81%D1%82%D1%8C" id="toc-скрытая-отчётность" class="nav-link" data-scroll-target="#%D1%81%D0%BA%D1%80%D1%8B%D1%82%D0%B0%D1%8F-%D0%BE%D1%82%D1%87%D1%91%D1%82%D0%BD%D0%BE%D1%81%D1%82%D1%8C"><span class="header-section-number">5.5.2</span> Скрытая отчётность</a></li>
  <li><a href="#sec-rfsd-coverage" id="toc-sec-rfsd-coverage" class="nav-link" data-scroll-target="#sec-rfsd-coverage"><span class="header-section-number">5.5.3</span> Какую часть экономики покрывает RFSD</a></li>
  <li><a href="#%D0%BE%D1%82%D1%87%D1%91%D1%82%D0%BD%D0%BE%D1%81%D1%82%D1%8C-%D1%8E%D1%80%D0%BB%D0%B8%D1%86%D0%B0-%D0%B0-%D0%BD%D0%B5-%D0%B3%D1%80%D1%83%D0%BF%D0%BF%D1%8B" id="toc-отчётность-юрлица-а-не-группы" class="nav-link" data-scroll-target="#%D0%BE%D1%82%D1%87%D1%91%D1%82%D0%BD%D0%BE%D1%81%D1%82%D1%8C-%D1%8E%D1%80%D0%BB%D0%B8%D1%86%D0%B0-%D0%B0-%D0%BD%D0%B5-%D0%B3%D1%80%D1%83%D0%BF%D0%BF%D1%8B"><span class="header-section-number">5.5.4</span> Отчётность юрлица, а не группы</a></li>
  <li><a href="#sec-rfsd-names" id="toc-sec-rfsd-names" class="nav-link" data-scroll-target="#sec-rfsd-names"><span class="header-section-number">5.5.5</span> Где взять названия компаний</a></li>
  </ul>
</li>
  <li>
<a href="#sec-ratios" id="toc-sec-ratios" class="nav-link" data-scroll-target="#sec-ratios"><span class="header-section-number">5.6</span> Финансовые коэффициенты</a>
  <ul class="collapse">
<li><a href="#sec-no-ebitda" id="toc-sec-no-ebitda" class="nav-link" data-scroll-target="#sec-no-ebitda"><span class="header-section-number">5.6.1</span> Чего нет в отчётности: амортизация и EBITDA</a></li>
  <li><a href="#%D0%BF%D0%BE%D1%87%D0%B5%D0%BC%D1%83-%D0%BC%D0%B5%D0%B4%D0%B8%D0%B0%D0%BD%D0%B0-%D0%B0-%D0%BD%D0%B5-%D1%81%D1%80%D0%B5%D0%B4%D0%BD%D0%B5%D0%B5" id="toc-почему-медиана-а-не-среднее" class="nav-link" data-scroll-target="#%D0%BF%D0%BE%D1%87%D0%B5%D0%BC%D1%83-%D0%BC%D0%B5%D0%B4%D0%B8%D0%B0%D0%BD%D0%B0-%D0%B0-%D0%BD%D0%B5-%D1%81%D1%80%D0%B5%D0%B4%D0%BD%D0%B5%D0%B5"><span class="header-section-number">5.6.2</span> Почему медиана, а не среднее</a></li>
  </ul>
</li>
  <li><a href="#sec-articulation" id="toc-sec-articulation" class="nav-link" data-scroll-target="#sec-articulation"><span class="header-section-number">5.7</span> Связь форм отчётности</a></li>
  <li><a href="#%D0%B8%D1%82%D0%BE%D0%B3%D0%B8" id="toc-итоги" class="nav-link" data-scroll-target="#%D0%B8%D1%82%D0%BE%D0%B3%D0%B8">Итоги</a></li>
  <li>
<a href="#sec-exercises-rfsd" id="toc-sec-exercises-rfsd" class="nav-link" data-scroll-target="#sec-exercises-rfsd"><span class="header-section-number">5.8</span> Упражнения</a>
  <ul class="collapse">
<li><a href="#%D0%B0.-%D0%BF%D0%BE%D0%BD%D0%B8%D0%BC%D0%B0%D0%BD%D0%B8%D0%B5" id="toc-а.-понимание" class="nav-link" data-scroll-target="#%D0%B0.-%D0%BF%D0%BE%D0%BD%D0%B8%D0%BC%D0%B0%D0%BD%D0%B8%D0%B5"><span class="header-section-number">5.8.1</span> А. Понимание</a></li>
  <li><a href="#%D0%B1.-%D0%BF%D1%80%D0%B0%D0%BA%D1%82%D0%B8%D0%BA%D0%B0-%D0%BD%D0%B0-%D1%81%D0%B2%D0%BE%D0%B5%D0%B9-%D0%BE%D1%82%D1%80%D0%B0%D1%81%D0%BB%D0%B8" id="toc-б.-практика-на-своей-отрасли" class="nav-link" data-scroll-target="#%D0%B1.-%D0%BF%D1%80%D0%B0%D0%BA%D1%82%D0%B8%D0%BA%D0%B0-%D0%BD%D0%B0-%D1%81%D0%B2%D0%BE%D0%B5%D0%B9-%D0%BE%D1%82%D1%80%D0%B0%D1%81%D0%BB%D0%B8"><span class="header-section-number">5.8.2</span> Б. Практика на своей отрасли</a></li>
  <li><a href="#%D0%B2.-%D1%80%D0%B0%D0%B1%D0%BE%D1%82%D0%B0-%D1%81-%D0%B8%D0%B8-%D0%B0%D1%81%D1%81%D0%B8%D1%81%D1%82%D0%B5%D0%BD%D1%82%D0%BE%D0%BC" id="toc-в.-работа-с-ии-ассистентом" class="nav-link" data-scroll-target="#%D0%B2.-%D1%80%D0%B0%D0%B1%D0%BE%D1%82%D0%B0-%D1%81-%D0%B8%D0%B8-%D0%B0%D1%81%D1%81%D0%B8%D1%81%D1%82%D0%B5%D0%BD%D1%82%D0%BE%D0%BC"><span class="header-section-number">5.8.3</span> В. Работа с ИИ-ассистентом</a></li>
  <li><a href="#%D0%B3.-%D0%BC%D0%B8%D0%BD%D0%B8-%D0%B8%D1%81%D1%81%D0%BB%D0%B5%D0%B4%D0%BE%D0%B2%D0%B0%D0%BD%D0%B8%D0%B5" id="toc-г.-мини-исследование" class="nav-link" data-scroll-target="#%D0%B3.-%D0%BC%D0%B8%D0%BD%D0%B8-%D0%B8%D1%81%D1%81%D0%BB%D0%B5%D0%B4%D0%BE%D0%B2%D0%B0%D0%BD%D0%B8%D0%B5"><span class="header-section-number">5.8.4</span> Г. Мини-исследование</a></li>
  </ul>
</li>
  <li><a href="#%D0%B2%D0%BE%D0%BF%D1%80%D0%BE%D1%81%D1%8B-%D0%B4%D0%BB%D1%8F-%D1%81%D0%B0%D0%BC%D0%BE%D0%BF%D1%80%D0%BE%D0%B2%D0%B5%D1%80%D0%BA%D0%B8" id="toc-вопросы-для-самопроверки" class="nav-link" data-scroll-target="#%D0%B2%D0%BE%D0%BF%D1%80%D0%BE%D1%81%D1%8B-%D0%B4%D0%BB%D1%8F-%D1%81%D0%B0%D0%BC%D0%BE%D0%BF%D1%80%D0%BE%D0%B2%D0%B5%D1%80%D0%BA%D0%B8">Вопросы для самопроверки</a></li>
  <li><a href="#%D1%87%D1%82%D0%BE-%D0%BF%D0%BE%D1%87%D0%B8%D1%82%D0%B0%D1%82%D1%8C" id="toc-что-почитать" class="nav-link" data-scroll-target="#%D1%87%D1%82%D0%BE-%D0%BF%D0%BE%D1%87%D0%B8%D1%82%D0%B0%D1%82%D1%8C">Что почитать</a></li>
  </ul></nav>
    </div>
<!-- main -->
<main class="content page-columns page-full" id="quarto-document-content"><header id="title-block-header" class="quarto-title-block default"><nav class="quarto-page-breadcrumbs quarto-title-breadcrumbs d-none d-lg-block" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./05-accounting-data.html">Корпоративная отчётность</a></li><li class="breadcrumb-item"><a href="./05-accounting-data.html"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Большие данные корпоративной отчётности</span></a></li></ol></nav><div class="quarto-title">
<h1 class="title">
<span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Большие данные корпоративной отчётности</span>
</h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header><!--
Материалы: ноутбуки Russian_corporate_data_RFSD_2025 и RFSD_2025_solution; rfsd.py;
данные – из проекта ../rfsd (RFSD v3, выгрузка scripts/build_data.py --rfsd-only).
Идеи из курса Рыбина (2025; только идеи): связь трёх форм, косвенный ОДДС, FCF ≈ −Δ чистого долга
(Модуль3_1, с. 26–40).
--><p>Выручка ПАО «Магнит» (ИНН 2309085638) по бухгалтерской отчётности за 2023 г. – 0,56 млрд руб. Не триллионы, как можно было бы ожидать от одной из крупнейших розничных сетей страны, а меньше миллиарда. При этом чистая прибыль той же компании – 98,3 млрд руб., в сотню с лишним раз больше выручки. Ошибка в данных? Нет. ПАО «Магнит» – холдинговая компания: магазины сети принадлежат его дочерней компании АО «Тандер» (ИНН 2310031475), выручка которой за тот же год составила 2,31 трлн руб. Прибыль холдинга почти целиком состоит из дивидендов дочерних компаний: 97,6 млрд руб. доходов от участия в других организациях. А в 2025 г., когда «Тандер» получил убыток (−22,5 млрд руб.), доходы от участия у холдинга равны 0, и его чистая прибыль сократилась до 5,4 млрд руб.</p>
<p>Этот пример показывает главное, что нужно знать о бухгалтерской отчётности российских компаний: она описывает <strong>отдельное юридическое лицо</strong>, а не группу компаний. Чтобы проанализировать бизнес, нужно понимать, какое юрлицо его ведёт, как устроены формы отчётности и какие ловушки в них встречаются. Зато в обмен на эту сложность мы получаем уникальный источник: отчётность <strong>всех</strong> российских организаций – 2,0 млн отчётов только за 2025 г. Открытые данные такого охвата о частных, а не только о публичных компаниях есть лишь в немногих странах.</p>
<div class="callout callout-style-simple callout-note callout-titled" title="В этой главе">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Уведомление</span>В этой главе
</div>
</div>
<div class="callout-body-container callout-body">
<ul>
<li>Узнаём, откуда берётся отчётность российских компаний и что такое набор данных RFSD.</li>
<li>Разбираемся в формах отчётности: баланс, отчёт о финансовых результатах, отчёт о движении денежных средств.</li>
<li>Учимся работать с большими таблицами в Polars: ленивые вычисления, фильтры, группировки.</li>
<li>Отбираем компании отрасли по классификатору ОКВЭД.</li>
<li>Проверяем качество отчётности и считаем финансовые коэффициенты.</li>
</ul>
<p><strong>Данные:</strong> <code>rfsd_sample.parquet</code> (выборка отчётности), <code>rfsd_summary.parquet</code>, <code>rfsd_cases.parquet</code>, <code>okved.csv</code>, <code>rfsd_lines.csv</code>. <strong>Нужно знать:</strong> основы бухгалтерского учёта (что такое активы, обязательства, выручка, прибыль), работа с pandas.</p>
</div>
</div>
<section id="sec-rfsd-source" class="level2 page-columns page-full" data-number="5.1"><h2 data-number="5.1" class="anchored" data-anchor-id="sec-rfsd-source">
<span class="header-section-number">5.1</span> Откуда берётся отчётность</h2>
<p>Российские организации обязаны ежегодно сдавать бухгалтерскую отчётность в налоговую службу. Исключения – банки и некоторые другие финансовые организации (они отчитываются перед Банком России), а также организации государственного сектора. Отчётность составляется по российским стандартам бухгалтерского учёта (<strong>РСБУ</strong>) на стандартных формах, где у каждой строки есть свой код. С 2019 г. эта отчётность собирается в государственном информационном ресурсе бухгалтерской отчётности (ГИР БО) и открыто публикуется на сайте ФНС.</p>
<p>Скачать с <a href="https://bo.nalog.gov.ru/">сайта ФНС</a> отчётность одной компании просто, а отчётность трёх миллионов компаний за полтора десятилетия – очень трудоёмко: данные нужно собрать, разобрать, привести к единому виду и очистить от ошибок. Есть коммерческие компании, которые продают такие наборы данных, но они стоят дорого и не всегда прозрачны. Также такие провайдеры (к примеру, СПАРК Интерфакс или ФИРА) не дают возможности работать с данными напрямую в Python или R, а только через их интерфейсы.</p>
<p>Эту работу проделали исследователи Европейского университета в Санкт-Петербурге и опубликовали результат как открытый набор данных <strong>RFSD</strong> (Russian Financial Statements Database) <span class="citation" data-cites="bondarkov2025">(<a href="references.html#ref-bondarkov2025" role="doc-biblioref">Bondarkov и др. 2025 г.</a>)</span>. Набор распространяется по лицензии CC BY 4.0 и доступен на платформе Hugging Face.</p>
<div class="no-row-height column-margin column-container"></div><div class="cell" data-layout-align="center">
<details open="" class="code-fold"><summary>Код</summary><div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb1"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a>s <span class="op">=</span> summary[summary[<span class="st">"year"</span>] <span class="op">&gt;=</span> <span class="dv">2012</span>]</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a>fig, ax <span class="op">=</span> plt.subplots()</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a>ax.bar(s[<span class="st">"year"</span>], s[<span class="st">"filed"</span>] <span class="op">/</span> <span class="fl">1e6</span>, color<span class="op">=</span><span class="st">"#34699A"</span>, label<span class="op">=</span><span class="st">"поданные отчёты"</span>)</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a>ax.plot(s[<span class="st">"year"</span>], s[<span class="st">"firms"</span>] <span class="op">/</span> <span class="fl">1e6</span>, color<span class="op">=</span><span class="st">"#C8702A"</span>, marker<span class="op">=</span><span class="st">"o"</span>, label<span class="op">=</span><span class="st">"все организации в наборе"</span>)</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a>ax.set_ylabel(<span class="st">"млн"</span>)</span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a>ax.legend(loc<span class="op">=</span><span class="st">"upper right"</span>)</span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a>plot.source(ax, <span class="st">"RFSD"</span>)</span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code></pre></div><button title="Скопировать текст" class="code-copy-button"><i class="bi"></i></button></div>
</details><div class="cell-output-display">
<div id="fig-rfsd-coverage" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure"><div aria-describedby="fig-rfsd-coverage-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="05-accounting-data_files/figure-html/fig-rfsd-coverage-1.svg" class="img-fluid quarto-figure quarto-figure-center figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-rfsd-coverage-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Рисунок&nbsp;5.1: Число отчётов в RFSD по годам
</figcaption></figure>
</div>
</div>
</div>
<p>В 2025 г. в наборе 3,1 млн организаций, из них отчётность подали 2,0 млн, а положительную выручку показали только 1,5 млн. Остальные – компании, освобождённые от сдачи отчётности, «спящие» юрлица без деятельности, фирмы в процессе ликвидации. Для анализа почти всегда нужны только поданные отчёты – в данных они отмечены флагом <code>filed = 1</code>.</p>
<p>Полный набор RFSD занимает около 8 ГБ: один год – это таблица примерно из 3 млн строк и более чем 200 столбцов. Для примеров этой главы мы используем выборку: компании пяти отраслей, выручка которых хотя бы в одном году 2018–2025 гг. превышала 1 млрд руб. Обратите внимание на «хотя бы в одном году»: так в выборку попадают и компании, которые потом сократились или ушли с рынка, и мы избегаем ошибки выжившего (глава «Подготовка данных»).</p>
<div class="cell" data-layout-align="center">
<details open="" class="code-fold"><summary>Код</summary><div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb2"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a>rfsd <span class="op">=</span> data.load_rfsd()</span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a>rfsd.groupby(rfsd[<span class="st">"okved"</span>].<span class="bu">str</span>[:<span class="dv">2</span>])[<span class="st">"inn"</span>].nunique()</span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; okved</span></span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; 10    2472</span></span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; 41    5350</span></span>
<span id="cb2-6"><a href="#cb2-6" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; 47    2996</span></span>
<span id="cb2-7"><a href="#cb2-7" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; 49    1849</span></span>
<span id="cb2-8"><a href="#cb2-8" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; 62    1377</span></span>
<span id="cb2-9"><a href="#cb2-9" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; Name: inn, dtype: int64</span></span></code></pre></div><button title="Скопировать текст" class="code-copy-button"><i class="bi"></i></button></div>
</details>
</div>
</section><section id="sec-forms" class="level2" data-number="5.2"><h2 data-number="5.2" class="anchored" data-anchor-id="sec-forms">
<span class="header-section-number">5.2</span> Формы отчётности</h2>
<p>Бухгалтерская отчётность состоит из нескольких форм. Для анализа важны три.</p>
<p><strong>Бухгалтерский баланс</strong> – снимок на конец года: что у компании есть (активы) и за счёт чего это финансируется (пассивы: капитал и обязательства). Активы всегда равны пассивам. <strong>Отчёт о финансовых результатах</strong> показывает, как из выручки через вычет расходов получается чистая прибыль. <strong>Отчёт о движении денежных средств</strong> показывает реальные поступления и платежи денег, разделённые на три вида деятельности: текущую (операционную), инвестиционную и финансовую.</p>
<p>В RFSD каждая строка формы – отдельный столбец с кодом строки: <code>line_1600</code> – итог баланса, <code>line_2110</code> – выручка. Основные строки:</p>
<div id="tbl-lines" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure"><figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-lines-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Таблица&nbsp;5.1: Основные строки бухгалтерской отчётности
</figcaption><div aria-describedby="tbl-lines-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead><tr class="header">
<th>Код</th>
<th>Строка</th>
<th>Форма</th>
</tr></thead>
<tbody>
<tr class="odd">
<td>1100 / 1200</td>
<td>Внеоборотные / оборотные активы</td>
<td>баланс</td>
</tr>
<tr class="even">
<td>1250</td>
<td>Денежные средства и эквиваленты</td>
<td>баланс</td>
</tr>
<tr class="odd">
<td>1600</td>
<td>Итого активы (баланс)</td>
<td>баланс</td>
</tr>
<tr class="even">
<td>1300</td>
<td>Капитал и резервы</td>
<td>баланс</td>
</tr>
<tr class="odd">
<td>1400 / 1500</td>
<td>Долгосрочные / краткосрочные обязательства</td>
<td>баланс</td>
</tr>
<tr class="even">
<td>1410 / 1510</td>
<td>Заёмные средства (долгосрочные / краткосрочные)</td>
<td>баланс</td>
</tr>
<tr class="odd">
<td>2110</td>
<td>Выручка</td>
<td>финансовые результаты</td>
</tr>
<tr class="even">
<td>2120</td>
<td>Себестоимость продаж</td>
<td>финансовые результаты</td>
</tr>
<tr class="odd">
<td>2200</td>
<td>Прибыль от продаж</td>
<td>финансовые результаты</td>
</tr>
<tr class="even">
<td>2330</td>
<td>Проценты к уплате</td>
<td>финансовые результаты</td>
</tr>
<tr class="odd">
<td>2300</td>
<td>Прибыль до налогообложения</td>
<td>финансовые результаты</td>
</tr>
<tr class="even">
<td>2400</td>
<td>Чистая прибыль</td>
<td>финансовые результаты</td>
</tr>
<tr class="odd">
<td>4100</td>
<td>Сальдо денежных потоков от текущих операций</td>
<td>движение денежных средств</td>
</tr>
<tr class="even">
<td>4500</td>
<td>Остаток денежных средств на конец периода</td>
<td>движение денежных средств</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<p>Полный справочник строк с названиями – в файле <code>rfsd_lines.csv</code>:</p>
<div class="cell" data-layout-align="center">
<details open="" class="code-fold"><summary>Код</summary><div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb3"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a>lines <span class="op">=</span> data.load_rfsd_lines()</span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a>lines[lines[<span class="st">"code"</span>].isin([<span class="st">"line_2110"</span>, <span class="st">"line_2120"</span>, <span class="st">"line_2330"</span>, <span class="st">"line_2400"</span>])][[<span class="st">"code"</span>, <span class="st">"name_ru"</span>, <span class="st">"sign"</span>]]</span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;          code                  name_ru                       sign</span></span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; 40  line_2110                  Выручка              положительная</span></span>
<span id="cb3-5"><a href="#cb3-5" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; 41  line_2120     Себестоимость продаж  в скобках (отрицательная)</span></span>
<span id="cb3-6"><a href="#cb3-6" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; 48  line_2330        Проценты к уплате  в скобках (отрицательная)</span></span>
<span id="cb3-7"><a href="#cb3-7" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; 60  line_2400  Чистая прибыль (убыток)                 любой знак</span></span></code></pre></div><button title="Скопировать текст" class="code-copy-button"><i class="bi"></i></button></div>
</details>
</div>
<p>Два соглашения нужно запомнить сразу.</p>
<p><strong>Единицы измерения – тысячи рублей.</strong> Выручка «Магнита» из введения записана в данных как 558&nbsp;670 – это 558&nbsp;670 тыс. руб., или 0,56 млрд руб.</p>
<p><strong>Расходы хранятся со знаком минус.</strong> В бумажных формах некоторые строки пишутся в скобках: себестоимость, коммерческие расходы, проценты к уплате. В RFSD такие строки хранятся отрицательными числами. Поэтому валовая прибыль – это <code>line_2110 + line_2120</code>, а не разность.</p>
<div class="callout callout-style-simple callout-warning callout-titled" title="Типичная ошибка">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Предупреждение</span>Типичная ошибка
</div>
</div>
<div class="callout-body-container callout-body">
<p>Использовать формулы, написанные для другой версии данных. В ранних версиях RFSD знаки строк «в скобках» были непоследовательны; после их исправления изменилась, в частности, чистая прибыль у 6–25% отчётов (в зависимости от года). Код, в котором прибыль до вычета процентов считается как <code>line_2300 + line_2330</code>, давал правильный ответ на старых данных и неправильный – на новых: теперь проценты отрицательны, и EBIT равен <code>line_2300 − line_2330</code>. Всегда проверяйте, какую версию данных вы используете, и знаки ключевых строк.</p>
</div>
</div>
</section><section id="sec-polars" class="level2" data-number="5.3"><h2 data-number="5.3" class="anchored" data-anchor-id="sec-polars">
<span class="header-section-number">5.3</span> Большие таблицы: Polars</h2>
<p>С таблицей в сотню тысяч строк pandas справляется легко. С таблицей в 3 млн строк и 200 столбцов – уже с трудом: pandas читает всё в память и выполняет каждую операцию по очереди. Для больших данных удобнее библиотека <strong>Polars</strong>. Она быстрее за счёт параллельных вычислений, но главное её преимущество – <strong>ленивые вычисления</strong>.</p>
<p>В ленивом режиме Polars не выполняет операции сразу, а строит <strong>план запроса</strong>. Когда результат действительно нужен (метод <code>collect()</code>), библиотека оптимизирует план: читает из файла только нужные столбцы, применяет фильтры прямо при чтении и не создаёт промежуточных таблиц. Посмотрим на примере: крупнейшие розничные компании в 2025 г.</p>
<div class="cell" data-layout-align="center">
<details open="" class="code-fold"><summary>Код</summary><div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb4"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a>lf <span class="op">=</span> pl.scan_parquet(<span class="st">"data/rfsd_sample.parquet"</span>)      <span class="co"># ничего не прочитано</span></span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a>top_retail <span class="op">=</span> (</span>
<span id="cb4-4"><a href="#cb4-4" aria-hidden="true" tabindex="-1"></a>    lf.<span class="bu">filter</span>((pl.col(<span class="st">"year"</span>) <span class="op">==</span> YEAR) <span class="op">&amp;</span> (pl.col(<span class="st">"filed"</span>) <span class="op">==</span> <span class="dv">1</span>)</span>
<span id="cb4-5"><a href="#cb4-5" aria-hidden="true" tabindex="-1"></a>              <span class="op">&amp;</span> pl.col(<span class="st">"okved"</span>).<span class="bu">str</span>.starts_with(<span class="st">"47"</span>))</span>
<span id="cb4-6"><a href="#cb4-6" aria-hidden="true" tabindex="-1"></a>      .select(<span class="st">"name"</span>, <span class="st">"inn"</span>, <span class="st">"okved"</span>, <span class="st">"line_2110"</span>, <span class="st">"line_2400"</span>)</span>
<span id="cb4-7"><a href="#cb4-7" aria-hidden="true" tabindex="-1"></a>      .with_columns((pl.col(<span class="st">"line_2110"</span>) <span class="op">/</span> <span class="fl">1e6</span>).alias(<span class="st">"выручка, млрд"</span>),</span>
<span id="cb4-8"><a href="#cb4-8" aria-hidden="true" tabindex="-1"></a>                    (pl.col(<span class="st">"line_2400"</span>) <span class="op">/</span> <span class="fl">1e6</span>).alias(<span class="st">"прибыль, млрд"</span>))</span>
<span id="cb4-9"><a href="#cb4-9" aria-hidden="true" tabindex="-1"></a>      .sort(<span class="st">"line_2110"</span>, descending<span class="op">=</span><span class="va">True</span>, nulls_last<span class="op">=</span><span class="va">True</span>)</span>
<span id="cb4-10"><a href="#cb4-10" aria-hidden="true" tabindex="-1"></a>      .head(<span class="dv">5</span>)</span>
<span id="cb4-11"><a href="#cb4-11" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb4-12"><a href="#cb4-12" aria-hidden="true" tabindex="-1"></a>top_retail.collect()</span></code></pre></div><button title="Скопировать текст" class="code-copy-button"><i class="bi"></i></button></div>
</details><div class="cell-output-display">
<div>
<style>
.dataframe > thead > tr,
.dataframe > tbody > tr {
  text-align: right;
  white-space: pre-wrap;
}
</style>
<small>shape: (5, 7)</small>
<table class="dataframe caption-top table table-sm table-striped small" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th">name</th>
<th data-quarto-table-cell-role="th">inn</th>
<th data-quarto-table-cell-role="th">okved</th>
<th data-quarto-table-cell-role="th">line_2110</th>
<th data-quarto-table-cell-role="th">line_2400</th>
<th data-quarto-table-cell-role="th">выручка, млрд</th>
<th data-quarto-table-cell-role="th">прибыль, млрд</th>
</tr>
<tr class="even">
<td>str</td>
<td>str</td>
<td>str</td>
<td>f64</td>
<td>f64</td>
<td>f64</td>
<td>f64</td>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>"ООО "АГРОТОРГ""</td>
<td>"7825706086"</td>
<td>"47.19"</td>
<td>3.4408e9</td>
<td>2.3904568e7</td>
<td>3440.848396</td>
<td>23.904568</td>
</tr>
<tr class="even">
<td>"АО "ТАНДЕР""</td>
<td>"2310031475"</td>
<td>"47.11"</td>
<td>3.0500e9</td>
<td>-2.2477921e7</td>
<td>3050.026081</td>
<td>-22.477921</td>
</tr>
<tr class="odd">
<td>"ООО "РВБ""</td>
<td>"9714053621"</td>
<td>"47.91.20"</td>
<td>1.1871e9</td>
<td>5.5322338e7</td>
<td>1187.129163</td>
<td>55.322338</td>
</tr>
<tr class="even">
<td>"АО "ТОРГОВЫЙ ДОМ "ПЕРЕКРЕСТОК""</td>
<td>"7728029110"</td>
<td>"47.11"</td>
<td>1.0386e9</td>
<td>1.1614455e7</td>
<td>1038.647866</td>
<td>11.614455</td>
</tr>
<tr class="odd">
<td>"ООО "АЛЬФА-М""</td>
<td>"7743931676"</td>
<td>"47.11"</td>
<td>8.46615845e8</td>
<td>2.6097579e7</td>
<td>846.615845</td>
<td>26.097579</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
<p>Обратите внимание на <code>nulls_last=True</code>: по умолчанию Polars при сортировке по убыванию ставит пропуски в начало, и без этого параметра «крупнейшими» оказались бы компании, не раскрывшие выручку.</p>
<p>До вызова <code>collect()</code> в переменной <code>top_retail</code> лежит не таблица, а описание запроса. Его можно посмотреть методом <code>top_retail.explain()</code>: в плане видно, что фильтр по году и коду выполняется при чтении файла, а из почти полусотни столбцов читаются только нужные для запроса.</p>
<p>Синтаксис Polars построен на <strong>выражениях</strong>: <code>pl.col("line_2110") / 1e6</code> – это не вычисление, а описание того, что нужно сделать со столбцом. Выражения передаются в методы <code>filter</code> (отбор строк), <code>select</code> (отбор и вычисление столбцов), <code>with_columns</code> (добавление столбцов), <code>group_by(...).agg(...)</code> (группировка). Та же задача в pandas выглядела бы так:</p>
<div class="cell" data-layout-align="center">
<details open="" class="code-fold"><summary>Код</summary><div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb5"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a>df23 <span class="op">=</span> rfsd[(rfsd[<span class="st">"year"</span>] <span class="op">==</span> YEAR) <span class="op">&amp;</span> (rfsd[<span class="st">"filed"</span>] <span class="op">==</span> <span class="dv">1</span>) <span class="op">&amp;</span> rfsd[<span class="st">"okved"</span>].<span class="bu">str</span>.startswith(<span class="st">"47"</span>)]</span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a>df23.nlargest(<span class="dv">5</span>, <span class="st">"line_2110"</span>)[[<span class="st">"name"</span>, <span class="st">"inn"</span>, <span class="st">"okved"</span>, <span class="st">"line_2110"</span>, <span class="st">"line_2400"</span>]]</span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;                                  name         inn  ...     line_2110   line_2400</span></span>
<span id="cb5-4"><a href="#cb5-4" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; 79898                  ООО "АГРОТОРГ"  7825706086  ...  3.440848e+09  23904568.0</span></span>
<span id="cb5-5"><a href="#cb5-5" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; 10704                     АО "ТАНДЕР"  2310031475  ...  3.050026e+09 -22477921.0</span></span>
<span id="cb5-6"><a href="#cb5-6" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; 86316                       ООО "РВБ"  9714053621  ...  1.187129e+09  55322338.0</span></span>
<span id="cb5-7"><a href="#cb5-7" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; 68492  АО "ТОРГОВЫЙ ДОМ "ПЕРЕКРЕСТОК"  7728029110  ...  1.038648e+09  11614455.0</span></span>
<span id="cb5-8"><a href="#cb5-8" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; 73520                   ООО "АЛЬФА-М"  7743931676  ...  8.466158e+08  26097579.0</span></span>
<span id="cb5-9"><a href="#cb5-9" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; </span></span>
<span id="cb5-10"><a href="#cb5-10" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; [5 rows x 5 columns]</span></span></code></pre></div><button title="Скопировать текст" class="code-copy-button"><i class="bi"></i></button></div>
</details>
</div>
<p>На небольшой выборке разницы в скорости не заметно. Но полный RFSD в pandas пришлось бы целиком загрузить в память, а Polars может читать его прямо с сервера, скачивая только нужные столбцы. Так выглядит запрос к полному набору за 2025 г. на Hugging Face (при сборке книги он не выполняется: файл за один год весит около 550 МБ):</p>
<div class="cell" data-layout-align="center">
<details open="" class="code-fold"><summary>Код</summary><div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb6"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a>url <span class="op">=</span> <span class="ss">f"hf://datasets/irlspbru/RFSD/RFSD/year=</span><span class="sc">{</span>YEAR<span class="sc">}</span><span class="ss">/part-0.parquet"</span></span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a>retail <span class="op">=</span> (</span>
<span id="cb6-4"><a href="#cb6-4" aria-hidden="true" tabindex="-1"></a>    pl.scan_parquet(url)</span>
<span id="cb6-5"><a href="#cb6-5" aria-hidden="true" tabindex="-1"></a>      .<span class="bu">filter</span>((pl.col(<span class="st">"filed"</span>) <span class="op">==</span> <span class="dv">1</span>) <span class="op">&amp;</span> pl.col(<span class="st">"okved"</span>).<span class="bu">str</span>.starts_with(<span class="st">"47"</span>))</span>
<span id="cb6-6"><a href="#cb6-6" aria-hidden="true" tabindex="-1"></a>      .select(<span class="st">"inn"</span>, <span class="st">"okved"</span>, <span class="st">"region"</span>, <span class="st">"line_2110"</span>, <span class="st">"line_2400"</span>, <span class="st">"line_1600"</span>)</span>
<span id="cb6-7"><a href="#cb6-7" aria-hidden="true" tabindex="-1"></a>      .collect()</span>
<span id="cb6-8"><a href="#cb6-8" aria-hidden="true" tabindex="-1"></a>)</span></code></pre></div><button title="Скопировать текст" class="code-copy-button"><i class="bi"></i></button></div>
</details>
</div>
<p>Этим способом вы будете работать с полными данными в проекте по анализу отрасли.</p>
</section><section id="sec-okved" class="level2" data-number="5.4"><h2 data-number="5.4" class="anchored" data-anchor-id="sec-okved">
<span class="header-section-number">5.4</span> Классификатор ОКВЭД</h2>
<p>Чтобы сравнивать компании, их нужно разделить на отрасли. В России для этого используется <strong>ОКВЭД 2</strong> – общероссийский классификатор видов экономической деятельности. Он иерархический: раздел (буква), класс (две цифры), подкласс, группа, подгруппа, вид.</p>
<div class="cell" data-layout-align="center">
<details open="" class="code-fold"><summary>Код</summary><div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb7"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a>okv <span class="op">=</span> data.load_okved()</span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a>okv[okv[<span class="st">"code"</span>].isin([<span class="st">"47"</span>, <span class="st">"47.1"</span>, <span class="st">"47.11"</span>, <span class="st">"47.19"</span>])][[<span class="st">"code"</span>, <span class="st">"section"</span>, <span class="st">"name"</span>]]</span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;        code section                                               name</span></span>
<span id="cb7-4"><a href="#cb7-4" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; 1756     47       G  Торговля розничная, кроме торговли автотранспо...</span></span>
<span id="cb7-5"><a href="#cb7-5" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; 1757   47.1       G  Торговля розничная в неспециализированных мага...</span></span>
<span id="cb7-6"><a href="#cb7-6" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; 1758  47.11       G  Торговля розничная преимущественно пищевыми пр...</span></span>
<span id="cb7-7"><a href="#cb7-7" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; 1762  47.19       G  Торговля розничная прочая в неспециализированн...</span></span></code></pre></div><button title="Скопировать текст" class="code-copy-button"><i class="bi"></i></button></div>
</details>
</div>
<p>Код <code>47</code> – класс «Торговля розничная», <code>47.11</code> – розничная торговля преимущественно продуктами в неспециализированных магазинах (так классифицируются продуктовые сети). У каждой компании в RFSD указан <strong>основной</strong> код ОКВЭД. Это важно учитывать: многие компании занимаются несколькими видами деятельности, а основной код иногда меняется.</p>
<p>В нашей выборке у 5,1% компаний основной код ОКВЭД менялся за 2018–2025 гг. Поэтому, отбирая компании отрасли, нужно решить, по какому году брать код, и описать это правило в работе.</p>
<div class="callout callout-style-simple callout-tip callout-titled" title="Сначала предскажите">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Совет</span>Сначала предскажите
</div>
</div>
<div class="callout-body-container callout-body">
<p>В каком из пяти классов нашей выборки – производство пищевых продуктов (10), строительство зданий (41), розничная торговля (47), сухопутный транспорт (49), разработка программного обеспечения (62) – медианная рентабельность продаж выше всего? А где ниже всего? Запишите ответ, прежде чем читать дальше.</p>
</div>
</div>
</section><section id="sec-rfsd-quality" class="level2" data-number="5.5"><h2 data-number="5.5" class="anchored" data-anchor-id="sec-rfsd-quality">
<span class="header-section-number">5.5</span> Качество данных</h2>
<p>Отчётность составляют сами компании, и ошибок в ней немало. Авторы RFSD проверили данные и пометили проблемные наблюдения флагами:</p>
<ul>
<li>
<code>filed</code> – отчёт действительно подан (а не восстановлен);</li>
<li>
<code>imputed</code> – значения восстановлены по отчёту следующего года;</li>
<li>
<code>outlier</code> – подозрительный отчёт, помеченный авторами набора после ручной проверки;</li>
<li>
<code>simplified</code> – упрощённая форма отчётности малого предприятия: в ней меньше строк.</li>
</ul>
<section id="сходится-ли-баланс" class="level3" data-number="5.5.1"><h3 data-number="5.5.1" class="anchored" data-anchor-id="сходится-ли-баланс">
<span class="header-section-number">5.5.1</span> Сходится ли баланс</h3>
<p>Самая простая проверка – равенство активов и пассивов: <code>line_1600 = line_1700</code>. Нарушить его в правильно составленной отчётности невозможно.</p>
<p>В полном наборе за 2025 г. баланс не сходится лишь в 0,47% отчётов – авторы RFSD исправили большинство ошибок. Но другая особенность встречается очень часто: у 17% поданных отчётов <strong>капитал неположительный</strong> – обязательства компании больше её активов. Для крупного бизнеса это редкость, а среди мелких компаний такие «фирмы с отрицательным капиталом» – обычное дело. Коэффициенты, в знаменателе которых стоит капитал (ROE, долг/капитал), для таких компаний теряют смысл, и их нужно исключать или рассматривать отдельно.</p>
</section><section id="скрытая-отчётность" class="level3" data-number="5.5.2"><h3 data-number="5.5.2" class="anchored" data-anchor-id="скрытая-отчётность">
<span class="header-section-number">5.5.2</span> Скрытая отчётность</h3>
<p>Не все компании публикуют отчётность открыто. Уже в первые годы работы ГИР БО некоторым организациям разрешили ограничивать доступ к своей отчётности – например, работающим в оборонной промышленности или находящимся под иностранными санкциями, – а после 2022 г. круг таких компаний заметно расширился. Отчётность они по-прежнему сдают в налоговую службу, но в ГИР БО она не публикуется. В RFSD у таких компаний пустые строки, а флаг <code>filed</code> равен нулю.</p>
<div class="cell" data-layout-align="center">
<details open="" class="code-fold"><summary>Код</summary><div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb8"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a>ozon <span class="op">=</span> cases[cases[<span class="st">"inn"</span>] <span class="op">==</span> <span class="st">"7704217370"</span>][[<span class="st">"inn"</span>, <span class="st">"year"</span>, <span class="st">"filed"</span>, <span class="st">"line_2110"</span>, <span class="st">"line_2400"</span>]]</span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a>ozon[ozon[<span class="st">"year"</span>] <span class="op">&gt;=</span> <span class="dv">2019</span>]</span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;            inn  year  filed    line_2110   line_2400</span></span>
<span id="cb8-4"><a href="#cb8-4" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; 38  7704217370  2019    0.0          NaN         NaN</span></span>
<span id="cb8-5"><a href="#cb8-5" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; 39  7704217370  2020    0.0          NaN         NaN</span></span>
<span id="cb8-6"><a href="#cb8-6" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; 40  7704217370  2021    0.0  177823485.0         0.0</span></span>
<span id="cb8-7"><a href="#cb8-7" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; 41  7704217370  2022    1.0  261369829.0 -48695018.0</span></span>
<span id="cb8-8"><a href="#cb8-8" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; 42  7704217370  2023    0.0          NaN         NaN</span></span>
<span id="cb8-9"><a href="#cb8-9" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; 43  7704217370  2024    0.0          NaN         NaN</span></span>
<span id="cb8-10"><a href="#cb8-10" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; 44  7704217370  2025    0.0          NaN         NaN</span></span></code></pre></div><button title="Скопировать текст" class="code-copy-button"><i class="bi"></i></button></div>
</details>
</div>
<p>ООО «Интернет Решения» (ИНН 7704217370) – основная операционная компания Ozon – за 2022 г. отчётность раскрыла, а за следующие годы – уже нет. И это не единичный случай. Посчитаем по полному RFSD, сколько крупных компаний – с выручкой не меньше 10 млрд руб. в последнем раскрытом отчёте – в каждом году не раскрыли отчётность, хотя продолжали работать.</p>
<div class="cell" data-layout-align="center">
<details open="" class="code-fold"><summary>Код</summary><div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb9"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a>hid <span class="op">=</span> data.load_rfsd_hidden()</span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a>hid[<span class="st">"доля по выручке"</span>] <span class="op">=</span> hid[<span class="st">"hidden_revenue"</span>] <span class="op">/</span> hid[<span class="st">"revenue"</span>]</span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a>fig, ax <span class="op">=</span> plt.subplots()</span>
<span id="cb9-4"><a href="#cb9-4" aria-hidden="true" tabindex="-1"></a>ax.bar(hid[<span class="st">"year"</span>], hid[<span class="st">"hidden"</span>], color<span class="op">=</span><span class="st">"#34699A"</span>)</span>
<span id="cb9-5"><a href="#cb9-5" aria-hidden="true" tabindex="-1"></a>ax.set_ylabel(<span class="st">"число компаний"</span>)</span>
<span id="cb9-6"><a href="#cb9-6" aria-hidden="true" tabindex="-1"></a>ax2 <span class="op">=</span> ax.twinx()</span>
<span id="cb9-7"><a href="#cb9-7" aria-hidden="true" tabindex="-1"></a>ax2.plot(hid[<span class="st">"year"</span>], hid[<span class="st">"доля по выручке"</span>], color<span class="op">=</span><span class="st">"#B8412E"</span>, marker<span class="op">=</span><span class="st">"o"</span>)</span>
<span id="cb9-8"><a href="#cb9-8" aria-hidden="true" tabindex="-1"></a>ax2.set_ylim(<span class="dv">0</span>, <span class="fl">0.5</span>)</span>
<span id="cb9-9"><a href="#cb9-9" aria-hidden="true" tabindex="-1"></a>ax2.yaxis.set_major_formatter(plt.FuncFormatter(<span class="kw">lambda</span> y, _: <span class="ss">f"</span><span class="sc">{</span>y<span class="sc">:.0%}</span><span class="ss">"</span>))</span>
<span id="cb9-10"><a href="#cb9-10" aria-hidden="true" tabindex="-1"></a>ax2.set_ylabel(<span class="st">"доля в выручке крупных компаний"</span>, color<span class="op">=</span><span class="st">"#B8412E"</span>)</span>
<span id="cb9-11"><a href="#cb9-11" aria-hidden="true" tabindex="-1"></a>plot.source(ax, <span class="st">"RFSD, расчёты автора"</span>)</span>
<span id="cb9-12"><a href="#cb9-12" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code></pre></div><button title="Скопировать текст" class="code-copy-button"><i class="bi"></i></button></div>
</details><div class="cell-output-display">
<div id="fig-hidden" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure"><div aria-describedby="fig-hidden-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="05-accounting-data_files/figure-html/fig-hidden-3.svg" class="img-fluid quarto-figure quarto-figure-center figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-hidden-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Рисунок&nbsp;5.2: Крупные компании, не раскрывшие отчётность: выручка не меньше 10 млрд руб. в последнем раскрытом отчёте
</figcaption></figure>
</div>
</div>
</div>
<p>В 2025 г. отчётность не раскрыли 839 из 4&nbsp;077 крупных компаний – 21%. По выручке это около 33% всех крупных компаний: скрываются прежде всего самые большие. Число таких компаний растёт: 118 в 2018 г., 612 в 2019 г. и 839 в 2025 г.</p>
<p>Резкий скачок в 2019 г. объясняется не только решениями о закрытии отчётности, но и сменой источника. До 2018 г. RFSD опирается на данные Росстата, куда отчётность попадала независимо от публичности, а с 2019 г. – на ГИР БО, где закрытая отчётность не публикуется. Поэтому у многих компаний последний раскрытый год в RFSD – 2018-й.</p>
<p>Вот крупнейшие из них в 2025 г.:</p>
<div class="cell" data-layout-align="center">
<details open="" class="code-fold"><summary>Код</summary><div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb10"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a>top_hidden.head(<span class="dv">10</span>).assign(last_revenue<span class="op">=</span><span class="kw">lambda</span> x: (x[<span class="st">"last_revenue"</span>] <span class="op">/</span> <span class="fl">1e6</span>).<span class="bu">round</span>(<span class="dv">0</span>))[</span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a>    [<span class="st">"name"</span>, <span class="st">"inn"</span>, <span class="st">"okved"</span>, <span class="st">"last_filed_year"</span>, <span class="st">"last_revenue"</span>]]</span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;                    name         inn     okved  last_filed_year  last_revenue</span></span>
<span id="cb10-4"><a href="#cb10-4" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; 0    ПАО "НК "РОСНЕФТЬ"  7706107510  06.10.10             2018        6968.0</span></span>
<span id="cb10-5"><a href="#cb10-5" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; 1                  None  9707001911     64.19             2023        3746.0</span></span>
<span id="cb10-6"><a href="#cb10-6" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; 2                  None  7707572492  70.10.20             2018        3130.0</span></span>
<span id="cb10-7"><a href="#cb10-7" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; 3   ПАО "ГАЗПРОМ НЕФТЬ"  5504036333     46.71             2021        2675.0</span></span>
<span id="cb10-8"><a href="#cb10-8" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; 4             ОАО "РЖД"  7708503727     49.20             2021        1964.0</span></span>
<span id="cb10-9"><a href="#cb10-9" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; 5  ПАО "СУРГУТНЕФТЕГАЗ"  8602060555  06.10.10             2018        1525.0</span></span>
<span id="cb10-10"><a href="#cb10-10" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; 6                  None  7842155505  71.12.20             2022        1180.0</span></span>
<span id="cb10-11"><a href="#cb10-11" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; 7      ПАО "ТРАНСНЕФТЬ"  7706061801  49.50.10             2018         938.0</span></span>
<span id="cb10-12"><a href="#cb10-12" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; 8    ПАО АНК "БАШНЕФТЬ"  0274051582  06.10.10             2018         755.0</span></span>
<span id="cb10-13"><a href="#cb10-13" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; 9                  None  6316031581     46.71             2021         730.0</span></span></code></pre></div><button title="Скопировать текст" class="code-copy-button"><i class="bi"></i></button></div>
</details>
</div>
<p>В списке – ПАО «НК «Роснефть» (ИНН 7706107510), ПАО «Газпром нефть» (ИНН 5504036333), ОАО «РЖД» (ИНН 7708503727), ПАО «Сургутнефтегаз» (ИНН 8602060555), ПАО «Транснефть» (ИНН 7706061801): компании, от которых зависят целые отрасли. Выручка в столбце <code>last_revenue</code> (млрд руб.) – из последнего раскрытого отчёта, иногда многолетней давности, так что это лишь ориентир размера.</p>
<p>Для отраслевого анализа это означает смещение: из данных выпадают прежде всего крупнейшие компании, в том числе под санкциями. В нефтедобыче, трубопроводном транспорте, металлургии анализ по RFSD описывает скорее «остальную» отрасль, чем отрасль целиком. Выводы о «всей отрасли» нужно делать осторожно и всегда проверять, не пропали ли из данных её лидеры. В следующей главе мы увидим, как исчезновение одной крупной компании меняет показатели концентрации.</p>
</section><section id="sec-rfsd-coverage" class="level3" data-number="5.5.3"><h3 data-number="5.5.3" class="anchored" data-anchor-id="sec-rfsd-coverage">
<span class="header-section-number">5.5.3</span> Какую часть экономики покрывает RFSD</h3>
<p>Насколько велик пробел из-за скрытой отчётности? Ответить помогает сравнение с официальной статистикой. Росстат публикует выручку организаций по видам деятельности, и в неё входят все организации, в том числе закрывшие отчётность от публики: статистическую отчётность они сдают по-прежнему. Ряды Росстата мы возьмём из rustata (набор <code>showdata/indicator_278140</code> «Выручка организаций», глава «Источники финансовых данных») и сравним с суммой выручки поданных отчётов в полном RFSD.</p>
<div class="cell" data-layout-align="center">
<details open="" class="code-fold"><summary>Код</summary><div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb11"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a>rs <span class="op">=</span> data.load_rosstat_revenue()                      <span class="co"># тыс. руб., как и в RFSD</span></span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a>rf <span class="op">=</span> data.load_rfsd_revenue_okved()</span>
<span id="cb11-3"><a href="#cb11-3" aria-hidden="true" tabindex="-1"></a>head <span class="op">=</span> rs[rs[<span class="st">"okved"</span>] <span class="op">==</span> <span class="st">"101.АГ"</span>].set_index(<span class="st">"year"</span>)[<span class="st">"revenue"</span>]   <span class="co"># «Всего по обследуемым видам»</span></span>
<span id="cb11-4"><a href="#cb11-4" aria-hidden="true" tabindex="-1"></a>coverage <span class="op">=</span> (rf.groupby(<span class="st">"year"</span>)[<span class="st">"revenue"</span>].<span class="bu">sum</span>() <span class="op">/</span> head).dropna().loc[<span class="dv">2018</span>:]</span>
<span id="cb11-5"><a href="#cb11-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-6"><a href="#cb11-6" aria-hidden="true" tabindex="-1"></a>fig, ax <span class="op">=</span> plt.subplots()</span>
<span id="cb11-7"><a href="#cb11-7" aria-hidden="true" tabindex="-1"></a>ax.plot(coverage.index, coverage, color<span class="op">=</span><span class="st">"#34699A"</span>, marker<span class="op">=</span><span class="st">"o"</span>)</span>
<span id="cb11-8"><a href="#cb11-8" aria-hidden="true" tabindex="-1"></a>ax.set_ylim(<span class="dv">0</span>, <span class="fl">1.05</span>)</span>
<span id="cb11-9"><a href="#cb11-9" aria-hidden="true" tabindex="-1"></a>ax.yaxis.set_major_formatter(plt.FuncFormatter(<span class="kw">lambda</span> y, _: <span class="ss">f"</span><span class="sc">{</span>y<span class="sc">:.0%}</span><span class="ss">"</span>))</span>
<span id="cb11-10"><a href="#cb11-10" aria-hidden="true" tabindex="-1"></a>plot.source(ax, <span class="st">"RFSD; Росстат (rustata.ru); расчёты автора"</span>)</span>
<span id="cb11-11"><a href="#cb11-11" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code></pre></div><button title="Скопировать текст" class="code-copy-button"><i class="bi"></i></button></div>
</details><div class="cell-output-display">
<div id="fig-rfsd-vs-rosstat" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure"><div aria-describedby="fig-rfsd-vs-rosstat-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="05-accounting-data_files/figure-html/fig-rfsd-vs-rosstat-5.svg" class="img-fluid quarto-figure quarto-figure-center figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-rfsd-vs-rosstat-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Рисунок&nbsp;5.3: Выручка в поданных отчётах RFSD в процентах от выручки организаций по данным Росстата
</figcaption></figure>
</div>
</div>
</div>
<p>В 2018 г. выручка в отчётах RFSD составляла 97% выручки организаций по данным Росстата, в 2025 г. – 76%. Четверть выручки экономики в открытых данных не видна. Посмотрим, в каких отраслях пробел больше всего (<a href="#fig-coverage-by-class" class="quarto-xref">Рисунок&nbsp;<span>5.4</span></a>).</p>
<div class="cell" data-layout-align="center">
<details open="" class="code-fold"><summary>Код</summary><div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb12"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a>m <span class="op">=</span> rf.merge(rs, on<span class="op">=</span>[<span class="st">"okved"</span>, <span class="st">"year"</span>], suffixes<span class="op">=</span>(<span class="st">"_rfsd"</span>, <span class="st">"_rosstat"</span>))</span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a>m[<span class="st">"охват"</span>] <span class="op">=</span> m[<span class="st">"revenue_rfsd"</span>] <span class="op">/</span> m[<span class="st">"revenue_rosstat"</span>]</span>
<span id="cb12-3"><a href="#cb12-3" aria-hidden="true" tabindex="-1"></a>top20 <span class="op">=</span> m[m[<span class="st">"year"</span>] <span class="op">==</span> YEAR].nlargest(<span class="dv">20</span>, <span class="st">"revenue_rosstat"</span>).sort_values(<span class="st">"охват"</span>)</span>
<span id="cb12-4"><a href="#cb12-4" aria-hidden="true" tabindex="-1"></a>labels <span class="op">=</span> top20[<span class="st">"okved"</span>] <span class="op">+</span> <span class="st">" "</span> <span class="op">+</span> top20[<span class="st">"name"</span>].<span class="bu">str</span>.<span class="bu">slice</span>(<span class="dv">0</span>, <span class="dv">38</span>)</span>
<span id="cb12-5"><a href="#cb12-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-6"><a href="#cb12-6" aria-hidden="true" tabindex="-1"></a>fig, ax <span class="op">=</span> plt.subplots(figsize<span class="op">=</span>(<span class="fl">6.5</span>, <span class="dv">5</span>))</span>
<span id="cb12-7"><a href="#cb12-7" aria-hidden="true" tabindex="-1"></a>ax.barh(labels, top20[<span class="st">"охват"</span>], color<span class="op">=</span>np.where(top20[<span class="st">"охват"</span>] <span class="op">&lt;</span> <span class="fl">0.5</span>, <span class="st">"#B8412E"</span>, <span class="st">"#34699A"</span>))</span>
<span id="cb12-8"><a href="#cb12-8" aria-hidden="true" tabindex="-1"></a>ax.axvline(<span class="dv">1</span>, color<span class="op">=</span><span class="st">"#6B7280"</span>, lw<span class="op">=</span><span class="fl">0.8</span>, ls<span class="op">=</span><span class="st">":"</span>)</span>
<span id="cb12-9"><a href="#cb12-9" aria-hidden="true" tabindex="-1"></a>ax.xaxis.set_major_formatter(plt.FuncFormatter(<span class="kw">lambda</span> x, _: <span class="ss">f"</span><span class="sc">{</span>x<span class="sc">:.0%}</span><span class="ss">"</span>))</span>
<span id="cb12-10"><a href="#cb12-10" aria-hidden="true" tabindex="-1"></a>ax.tick_params(axis<span class="op">=</span><span class="st">"y"</span>, labelsize<span class="op">=</span><span class="dv">7</span>)</span>
<span id="cb12-11"><a href="#cb12-11" aria-hidden="true" tabindex="-1"></a>plot.source(ax, <span class="st">"RFSD; Росстат (rustata.ru); расчёты автора"</span>)</span>
<span id="cb12-12"><a href="#cb12-12" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code></pre></div><button title="Скопировать текст" class="code-copy-button"><i class="bi"></i></button></div>
</details><div class="cell-output-display">
<div id="fig-coverage-by-class" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure"><div aria-describedby="fig-coverage-by-class-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="05-accounting-data_files/figure-html/fig-coverage-by-class-7.svg" class="img-fluid quarto-figure quarto-figure-center figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-coverage-by-class-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Рисунок&nbsp;5.4: Охват RFSD по 20 крупнейшим классам ОКВЭД (по выручке по данным Росстата) в 2025 г.
</figcaption></figure>
</div>
</div>
</div>
<p>Крупнейшие по выручке классы делятся на две группы. В торговле, строительстве, пищевой промышленности RFSD покрывает почти всю выручку: в розничной торговле 94%, в строительстве зданий 102%. А в производстве нефтепродуктов (класс 19) – 15%, в металлургии (24) – 26%, в добыче нефти и газа (06) – 38%. За пределами двадцатки охват бывает ещё ниже: в производстве прочих транспортных средств, куда входят авиа- и судостроение (класс 30), – 13%, в производстве электроники (26) – 28%. Вероятная причина – в этих отраслях много компаний оборонной промышленности и компаний под санкциями, которые закрыли отчётность. Анализ таких отраслей по RFSD описывает меньшую и нетипичную их часть.</p>
<p>Сравнение приблизительное. Росстат относит организацию к отрасли по данным своего статистического регистра, а в RFSD указан код ОКВЭД из реестра юрлиц, и они не всегда совпадают. Примеры – ПАО «НК «Роснефть» и ПАО «Газпром нефть» (ИНН 5504036333): в RFSD у них коды 06.10.10 (добыча нефти) и 46.71 (оптовая торговля топливом), а в выписках ЕГРЮЛ основным видом деятельности по данным Росстата указано производство нефтепродуктов (19.20.9 и 19.20.1). Поэтому охват по отдельным классам бывает больше 100%: например, для деятельности головных офисов (класс 70) – 158%, по-видимому, потому что многие холдинги записаны в реестре юрлиц под этим кодом, а Росстат относит их к отрасли основного бизнеса. Кроме того, в рядах Росстата есть методологический разрыв между 2017 и 2018 г.: например, выручка по финансовым услугам (класс 64) за 2017 г. в восемь раз больше, чем за 2018 г. Поэтому сравнение начинается с 2018 г.</p>
</section><section id="отчётность-юрлица-а-не-группы" class="level3" data-number="5.5.4"><h3 data-number="5.5.4" class="anchored" data-anchor-id="отчётность-юрлица-а-не-группы">
<span class="header-section-number">5.5.4</span> Отчётность юрлица, а не группы</h3>
<p>Пример «Магнита» из начала главы – не исключение. Крупные группы компаний обычно состоят из десятков юрлиц: холдинга, операционных компаний, финансовых и управляющих компаний. Отчётность по РСБУ каждого из них – это часть картины. Отчётность группы в целом (консолидированная, по МСФО) в RFSD не входит. Поэтому, анализируя крупную компанию, сначала выясните, какое юрлицо ведёт основной бизнес.</p>
</section><section id="sec-rfsd-names" class="level3" data-number="5.5.5"><h3 data-number="5.5.5" class="anchored" data-anchor-id="sec-rfsd-names">
<span class="header-section-number">5.5.5</span> Где взять названия компаний</h3>
<p>В RFSD нет названий компаний – только идентификаторы: ИНН (<code>inn</code>) и ОГРН (<code>ogrn</code>). Так сделано намеренно: названия меняются, пишутся по-разному и не уникальны, а ИНН однозначно определяет юрлицо на всём периоде. Поэтому связывать данные всегда нужно по ИНН, а название – лишь подпись для читателя.</p>
<p>Столбец <code>name</code> в нашей выборке добавлен отдельно: названия найдены для 96% компаний. Если вам понадобятся названия для своих данных, есть несколько способов.</p>
<ul>
<li>
<strong>Сайт ГИР БО</strong> (<a href="https://bo.nalog.gov.ru/">bo.nalog.gov.ru</a>). Поиск по ИНН показывает название и отчётность компании. Для нескольких компаний удобно искать вручную. Для сотен компаний можно отправлять запросы из программы, как в примере ниже, но это неофициальный интерфейс сайта: он может измениться, а запросы нужно отправлять не чаще нескольких раз в секунду.</li>
<li>
<strong>Сервис ФНС «Предоставление сведений из ЕГРЮЛ/ЕГРИП»</strong> (<a href="https://egrul.nalog.gov.ru/">egrul.nalog.gov.ru</a>) – выписка из реестра юрлиц по ИНН: полное и краткое название, адрес, дата регистрации и ликвидации. Подходит для проверки отдельных компаний.</li>
<li>
<strong>Коммерческие базы</strong> (СПАРК-Интерфакс, Контур.Фокус) дают названия, связи между компаниями и группы, но платно и обычно через собственный интерфейс.</li>
<li>
<strong>Для публичных компаний</strong> ИНН эмитента указан в раскрытии информации (например, на сайте e-disclosure.ru), и по нему отчётность связывается с тикером на бирже.</li>
</ul>
<div class="cell" data-layout-align="center">
<details open="" class="code-fold"><summary>Код</summary><div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb13"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> time</span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> requests</span>
<span id="cb13-3"><a href="#cb13-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-4"><a href="#cb13-4" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> bo_name(inn: <span class="bu">str</span>) <span class="op">-&gt;</span> <span class="bu">str</span> <span class="op">|</span> <span class="va">None</span>:</span>
<span id="cb13-5"><a href="#cb13-5" aria-hidden="true" tabindex="-1"></a>    <span class="co">"""Краткое название организации по ИНН из поиска ГИР БО (неофициальный интерфейс)."""</span></span>
<span id="cb13-6"><a href="#cb13-6" aria-hidden="true" tabindex="-1"></a>    r <span class="op">=</span> requests.get(<span class="st">"https://bo.nalog.gov.ru/advanced-search/organizations/search"</span>,</span>
<span id="cb13-7"><a href="#cb13-7" aria-hidden="true" tabindex="-1"></a>                     params<span class="op">=</span>{<span class="st">"query"</span>: inn, <span class="st">"page"</span>: <span class="dv">0</span>}, timeout<span class="op">=</span><span class="dv">30</span>)</span>
<span id="cb13-8"><a href="#cb13-8" aria-hidden="true" tabindex="-1"></a>    <span class="cf">for</span> org <span class="kw">in</span> r.json().get(<span class="st">"content"</span>, []):</span>
<span id="cb13-9"><a href="#cb13-9" aria-hidden="true" tabindex="-1"></a>        <span class="cf">if</span> org.get(<span class="st">"inn"</span>, <span class="st">""</span>).replace(<span class="st">"&lt;strong&gt;"</span>, <span class="st">""</span>).replace(<span class="st">"&lt;/strong&gt;"</span>, <span class="st">""</span>) <span class="op">==</span> inn:</span>
<span id="cb13-10"><a href="#cb13-10" aria-hidden="true" tabindex="-1"></a>            <span class="cf">return</span> org.get(<span class="st">"shortName"</span>)</span>
<span id="cb13-11"><a href="#cb13-11" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> <span class="va">None</span></span>
<span id="cb13-12"><a href="#cb13-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-13"><a href="#cb13-13" aria-hidden="true" tabindex="-1"></a>names <span class="op">=</span> {}</span>
<span id="cb13-14"><a href="#cb13-14" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> inn <span class="kw">in</span> [<span class="st">"2310031475"</span>, <span class="st">"7825706086"</span>]:</span>
<span id="cb13-15"><a href="#cb13-15" aria-hidden="true" tabindex="-1"></a>    names[inn] <span class="op">=</span> bo_name(inn)</span>
<span id="cb13-16"><a href="#cb13-16" aria-hidden="true" tabindex="-1"></a>    time.sleep(<span class="fl">0.5</span>)                                    <span class="co"># не перегружать сервис</span></span></code></pre></div><button title="Скопировать текст" class="code-copy-button"><i class="bi"></i></button></div>
</details>
</div>
<p>У компаний, скрывших отчётность (подраздел «Скрытая отчётность» выше), названия обычно не находятся и в поиске ГИР БО: их там просто нет. Например, ООО «Яндекс» (ИНН 7736207543) раскрыло отчётность за 2024 г., но не за 2025 г., и в поиске ГИР БО компания уже не видна. Для таких компаний название нужно брать из выписки ЕГРЮЛ по ИНН или из раскрытия информации эмитента.</p>
<div class="callout callout-style-simple callout-important callout-titled" title="Особенность данных: новые формы с 2025 г.">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Важное уведомление</span>Особенность данных: новые формы с 2025 г.
</div>
</div>
<div class="callout-body-container callout-body">
<p>С отчётности за 2025 г. в России действуют новые формы. Коды части строк изменились: например, в упрощённой форме дебиторская задолженность отражается по строке 1240 вместо 1230. RFSD сохраняет коды в том виде, в каком они были в формах соответствующего года, поэтому при анализе рядов, включающих 2025 г., нужно сверять коды. В нашей выборке есть 2025 г., и в примерах мы учитываем эту особенность. Кроме того, для последнего года в RFSD нет восстановленных значений (<code>imputed</code>): их восстанавливают по отчёту следующего года, которого ещё нет.</p>
</div>
</div>
</section></section><section id="sec-ratios" class="level2" data-number="5.6"><h2 data-number="5.6" class="anchored" data-anchor-id="sec-ratios">
<span class="header-section-number">5.6</span> Финансовые коэффициенты</h2>
<p>Абсолютные показатели компаний разного размера сравнивать бессмысленно: выручка «Тандера» в тысячи раз больше выручки небольшой сети. Поэтому анализ отчётности строится на <strong>финансовых коэффициентах</strong> – отношениях показателей друг к другу.</p>
<div id="tbl-ratios" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure"><figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-ratios-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Таблица&nbsp;5.2: Основные финансовые коэффициенты
</figcaption><div aria-describedby="tbl-ratios-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead><tr class="header">
<th>Коэффициент</th>
<th>Формула в RFSD</th>
<th>Что показывает</th>
</tr></thead>
<tbody>
<tr class="odd">
<td>Рентабельность продаж (ROS)</td>
<td><code>line_2400 / line_2110</code></td>
<td>сколько чистой прибыли приносит рубль выручки</td>
</tr>
<tr class="even">
<td>Рентабельность активов (ROA)</td>
<td><code>line_2400 / line_1600</code></td>
<td>сколько прибыли приносит рубль активов</td>
</tr>
<tr class="odd">
<td>Рентабельность капитала (ROE)</td>
<td><code>line_2400 / line_1300</code></td>
<td>сколько прибыли приносит рубль капитала собственников</td>
</tr>
<tr class="even">
<td>Оборачиваемость активов</td>
<td><code>line_2110 / line_1600</code></td>
<td>сколько выручки приносит рубль активов</td>
</tr>
<tr class="odd">
<td>Текущая ликвидность</td>
<td><code>line_1200 / line_1500</code></td>
<td>хватает ли оборотных активов на краткосрочные обязательства</td>
</tr>
<tr class="even">
<td>Долг / капитал</td>
<td><code>(line_1410 + line_1510) / line_1300</code></td>
<td>долговая нагрузка</td>
</tr>
<tr class="odd">
<td>Покрытие процентов</td>
<td><code>(line_2300 − line_2330) / (−line_2330)</code></td>
<td>во сколько раз операционная прибыль превышает проценты</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<p>Посчитаем их для всех компаний выборки в 2025 г.:</p>
<div class="cell" data-layout-align="center">
<details open="" class="code-fold"><summary>Код</summary><div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb14"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a>d <span class="op">=</span> data.load_rfsd(years<span class="op">=</span>YEAR)</span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a>d <span class="op">=</span> d[d[<span class="st">"filed"</span>] <span class="op">==</span> <span class="dv">1</span>].copy()</span>
<span id="cb14-3"><a href="#cb14-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-4"><a href="#cb14-4" aria-hidden="true" tabindex="-1"></a>pos <span class="op">=</span> <span class="kw">lambda</span> x: x.where(x <span class="op">&gt;</span> <span class="dv">0</span>)                    <span class="co"># знаменатель должен быть положительным</span></span>
<span id="cb14-5"><a href="#cb14-5" aria-hidden="true" tabindex="-1"></a>d[<span class="st">"ros"</span>] <span class="op">=</span> d[<span class="st">"line_2400"</span>] <span class="op">/</span> pos(d[<span class="st">"line_2110"</span>])</span>
<span id="cb14-6"><a href="#cb14-6" aria-hidden="true" tabindex="-1"></a>d[<span class="st">"roa"</span>] <span class="op">=</span> d[<span class="st">"line_2400"</span>] <span class="op">/</span> pos(d[<span class="st">"line_1600"</span>])</span>
<span id="cb14-7"><a href="#cb14-7" aria-hidden="true" tabindex="-1"></a>d[<span class="st">"roe"</span>] <span class="op">=</span> d[<span class="st">"line_2400"</span>] <span class="op">/</span> pos(d[<span class="st">"line_1300"</span>])</span>
<span id="cb14-8"><a href="#cb14-8" aria-hidden="true" tabindex="-1"></a>d[<span class="st">"turnover"</span>] <span class="op">=</span> d[<span class="st">"line_2110"</span>] <span class="op">/</span> pos(d[<span class="st">"line_1600"</span>])</span>
<span id="cb14-9"><a href="#cb14-9" aria-hidden="true" tabindex="-1"></a>d[<span class="st">"current"</span>] <span class="op">=</span> d[<span class="st">"line_1200"</span>] <span class="op">/</span> pos(d[<span class="st">"line_1500"</span>])</span>
<span id="cb14-10"><a href="#cb14-10" aria-hidden="true" tabindex="-1"></a>d[<span class="st">"ebit"</span>] <span class="op">=</span> d[<span class="st">"line_2300"</span>] <span class="op">-</span> d[<span class="st">"line_2330"</span>].fillna(<span class="dv">0</span>)</span>
<span id="cb14-11"><a href="#cb14-11" aria-hidden="true" tabindex="-1"></a>d[<span class="st">"coverage"</span>] <span class="op">=</span> d[<span class="st">"ebit"</span>] <span class="op">/</span> pos(<span class="op">-</span>d[<span class="st">"line_2330"</span>])</span>
<span id="cb14-12"><a href="#cb14-12" aria-hidden="true" tabindex="-1"></a>d[<span class="st">"div"</span>] <span class="op">=</span> d[<span class="st">"okved"</span>].<span class="bu">str</span>[:<span class="dv">2</span>]</span>
<span id="cb14-13"><a href="#cb14-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-14"><a href="#cb14-14" aria-hidden="true" tabindex="-1"></a>ratios <span class="op">=</span> [<span class="st">"ros"</span>, <span class="st">"roa"</span>, <span class="st">"roe"</span>, <span class="st">"turnover"</span>, <span class="st">"current"</span>, <span class="st">"coverage"</span>]</span>
<span id="cb14-15"><a href="#cb14-15" aria-hidden="true" tabindex="-1"></a>d.groupby(<span class="st">"div"</span>)[ratios].median().<span class="bu">round</span>(<span class="dv">3</span>)</span>
<span id="cb14-16"><a href="#cb14-16" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;        ros    roa    roe  turnover  current  coverage</span></span>
<span id="cb14-17"><a href="#cb14-17" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; div                                                  </span></span>
<span id="cb14-18"><a href="#cb14-18" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; 10   0.017  0.038  0.154     1.950    1.466     2.669</span></span>
<span id="cb14-19"><a href="#cb14-19" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; 41   0.011  0.011  0.186     1.091    1.081     4.262</span></span>
<span id="cb14-20"><a href="#cb14-20" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; 47   0.011  0.028  0.183     2.562    1.187     2.089</span></span>
<span id="cb14-21"><a href="#cb14-21" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; 49   0.008  0.014  0.122     1.454    1.031     1.922</span></span>
<span id="cb14-22"><a href="#cb14-22" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; 62   0.055  0.084  0.281     1.539    1.532     8.942</span></span></code></pre></div><button title="Скопировать текст" class="code-copy-button"><i class="bi"></i></button></div>
</details>
</div>
<p>Медианная рентабельность продаж выше всего в классе 62 (разработка программного обеспечения) – 5,5%, ниже всего в классе 49 (сухопутный транспорт) – 0,8%. Разница во многом объясняется бизнес-моделью: разработчику программ почти не нужны материальные активы и закупки, транспортные компании несут большие расходы на содержание дорогих основных средств, а строители и розничные сети работают с большими объёмами при небольшой наценке. На уровне рентабельности сказывается и год: в 2025 г. маржа снизилась во всех пяти отраслях (в следующей главе мы посмотрим на её динамику). Зато у розницы высокая оборачиваемость активов: магазин быстро продаёт товар и снова закупает его. Эту связь маржи и оборачиваемости мы разберём в следующей главе с помощью разложения DuPont.</p>
<section id="sec-no-ebitda" class="level3" data-number="5.6.1"><h3 data-number="5.6.1" class="anchored" data-anchor-id="sec-no-ebitda">
<span class="header-section-number">5.6.1</span> Чего нет в отчётности: амортизация и EBITDA</h3>
<p>В аналитике и в новостях о компаниях постоянно встречается показатель <strong>EBITDA</strong> – прибыль до вычета процентов, налогов и амортизации (Earnings Before Interest, Taxes, Depreciation and Amortization). На нём основаны самые популярные мерки долговой нагрузки: отношение чистого долга к EBITDA, ковенанты в кредитных договорах, мультипликатор EV/EBITDA. Естественно захотеть посчитать EBITDA по данным RFSD. Сделать это корректно нельзя.</p>
<p>Причина в устройстве российской отчётности. EBITDA = EBIT + амортизация. EBIT мы посчитали выше, а вот амортизации нет ни в одной из строк RFSD:</p>
<ul>
<li>в отчёте о финансовых результатах (форма 2) расходы сгруппированы по функциям – себестоимость, коммерческие, управленческие, – и амортизация «растворена» в них;</li>
<li>отчёт о движении денежных средств (форма 4) по РСБУ составляется прямым методом: в нём показаны реальные поступления и платежи, а не корректировка прибыли на неденежные расходы, как в косвенном методе МСФО. Поэтому амортизации нет и там;</li>
<li>амортизация раскрывается в пояснениях к отчётности (строка 5640 «Амортизация» в разделе о затратах на производство), но пояснения в RFSD не входят, а многие компании, сдающие упрощённую отчётность, их не составляют вовсе.</li>
</ul>
<p>Иногда амортизацию просто пропускают и называют EBITDA то, что на самом деле является EBIT. Для разработчика программ, у которого основные средства составляют в среднем (по медиане) 3% активов, ошибка будет небольшой. Для транспортной компании, у которой на основные средства приходится 39% активов, амортизация – одна из крупнейших статей затрат, и «EBITDA», посчитанная без неё, окажется сильно заниженной. Отношение долга к такой «EBITDA» будет завышено, и компания будет выглядеть более закредитованной, чем при расчёте по её опубликованной отчётности. Хуже того, ошибка разная для разных отраслей, поэтому искажаются и сравнения между ними.</p>
<p>Что делать на практике:</p>
<ul>
<li>по данным RFSD использовать показатели, которые считаются честно: EBIT, прибыль от продаж (<code>line_2200</code>), чистую прибыль – и называть их своими именами;</li>
<li>если нужна долговая нагрузка, считать долг к EBIT и помнить, что пороги, привычные для долга к EBITDA (например, «больше 3–4 – высокая нагрузка»), к нему не применимы: при той же компании отношение к EBIT всегда выше;</li>
<li>для публичных компаний брать EBITDA из консолидированной отчётности по МСФО или раскрытий эмитента и указывать источник.</li>
</ul>
<div class="callout callout-style-simple callout-warning callout-titled" title="Типичная ошибка">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Предупреждение</span>Типичная ошибка
</div>
</div>
<div class="callout-body-container callout-body">
<p>Назвать EBITDA показатель без амортизации. В прошлые годы в учебных ноутбуках этого курса EBITDA по RFSD считалась «упрощённо, как EBIT». Название обещает читателю одно, а число означает другое. Если нужного показателя в данных нет, так и напишите и используйте ближайший корректный показатель с его настоящим названием.</p>
</div>
</div>
</section><section id="почему-медиана-а-не-среднее" class="level3" data-number="5.6.2"><h3 data-number="5.6.2" class="anchored" data-anchor-id="почему-медиана-а-не-среднее">
<span class="header-section-number">5.6.2</span> Почему медиана, а не среднее</h3>
<p>Распределения финансовых коэффициентов очень неравномерны. Посмотрим на ROE:</p>
<div class="cell" data-layout-align="center">
<details open="" class="code-fold"><summary>Код</summary><div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb15"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a>roe <span class="op">=</span> d[<span class="st">"roe"</span>].dropna()</span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a>fig, ax <span class="op">=</span> plt.subplots()</span>
<span id="cb15-3"><a href="#cb15-3" aria-hidden="true" tabindex="-1"></a>ax.hist(roe.clip(<span class="op">-</span><span class="dv">1</span>, <span class="dv">2</span>), bins<span class="op">=</span><span class="dv">80</span>, color<span class="op">=</span><span class="st">"#34699A"</span>)</span>
<span id="cb15-4"><a href="#cb15-4" aria-hidden="true" tabindex="-1"></a>ax.axvline(roe.median(), color<span class="op">=</span><span class="st">"#B8412E"</span>, lw<span class="op">=</span><span class="fl">1.2</span>, label<span class="op">=</span><span class="ss">f"медиана </span><span class="sc">{</span>roe<span class="sc">.</span>median()<span class="sc">:.0%}</span><span class="ss">"</span>)</span>
<span id="cb15-5"><a href="#cb15-5" aria-hidden="true" tabindex="-1"></a>ax.axvline(roe.mean(), color<span class="op">=</span><span class="st">"#C8702A"</span>, lw<span class="op">=</span><span class="fl">1.2</span>, ls<span class="op">=</span><span class="st">"--"</span>, label<span class="op">=</span><span class="ss">f"среднее </span><span class="sc">{</span>roe<span class="sc">.</span>mean()<span class="sc">:.0%}</span><span class="ss">"</span>)</span>
<span id="cb15-6"><a href="#cb15-6" aria-hidden="true" tabindex="-1"></a>ax.set_xlabel(<span class="st">"ROE (значения за пределами от −100% до 200% прижаты к краям)"</span>)</span>
<span id="cb15-7"><a href="#cb15-7" aria-hidden="true" tabindex="-1"></a>ax.xaxis.set_major_formatter(plt.FuncFormatter(<span class="kw">lambda</span> x, _: <span class="ss">f"</span><span class="sc">{</span>x<span class="sc">:.0%}</span><span class="ss">"</span>))</span>
<span id="cb15-8"><a href="#cb15-8" aria-hidden="true" tabindex="-1"></a>ax.legend()</span>
<span id="cb15-9"><a href="#cb15-9" aria-hidden="true" tabindex="-1"></a>plot.source(ax, <span class="st">"RFSD, расчёты автора"</span>, offset<span class="op">=</span><span class="dv">32</span>)</span>
<span id="cb15-10"><a href="#cb15-10" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code></pre></div><button title="Скопировать текст" class="code-copy-button"><i class="bi"></i></button></div>
</details><div class="cell-output-display">
<div id="fig-roe-dist" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure"><div aria-describedby="fig-roe-dist-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="05-accounting-data_files/figure-html/fig-roe-dist-9.svg" class="img-fluid quarto-figure quarto-figure-center figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-roe-dist-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Рисунок&nbsp;5.5: Распределение рентабельности капитала (ROE) компаний выборки в 2025 г.
</figcaption></figure>
</div>
</div>
</div>
<p>Один процент компаний с самой низкой ROE имеет рентабельность ниже −434%, один процент с самой высокой – выше 2&nbsp;589%. Такие значения возникают, когда капитал компании очень мал: небольшая прибыль, делённая на почти нулевой капитал, даёт тысячи процентов. Среднее значение по отрасли оказывается во власти этих крайних случаев, а медиана и квантили – устойчивы. Поэтому для отраслевых сравнений используют медиану и межквартильный размах, а крайние значения либо исключают, либо «прижимают» к заданным квантилям (<strong>винсоризация</strong>).</p>
</section></section><section id="sec-articulation" class="level2" data-number="5.7"><h2 data-number="5.7" class="anchored" data-anchor-id="sec-articulation">
<span class="header-section-number">5.7</span> Связь форм отчётности</h2>
<p>Формы отчётности связаны между собой, и эти связи – ещё одна проверка данных и источник содержательных выводов.</p>
<p><strong>Деньги в двух формах.</strong> Остаток денежных средств на конец года в отчёте о движении денежных средств (<code>line_4500</code>) должен совпадать с денежными средствами в балансе (<code>line_1250</code>).</p>
<div class="cell" data-layout-align="center">
<details open="" class="code-fold"><summary>Код</summary><div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb16"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a>both <span class="op">=</span> d[d[<span class="st">"line_4500"</span>].notna() <span class="op">&amp;</span> d[<span class="st">"line_1250"</span>].notna()]</span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a>match <span class="op">=</span> (both[<span class="st">"line_4500"</span>] <span class="op">-</span> both[<span class="st">"line_1250"</span>]).<span class="bu">abs</span>() <span class="op">&lt;=</span> <span class="dv">5</span>      <span class="co"># допуск на округление</span></span>
<span id="cb16-3"><a href="#cb16-3" aria-hidden="true" tabindex="-1"></a>match.mean()</span>
<span id="cb16-4"><a href="#cb16-4" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; 0.9307426789889768</span></span></code></pre></div><button title="Скопировать текст" class="code-copy-button"><i class="bi"></i></button></div>
</details>
</div>
<p>Совпадение – в 93% отчётов. Остальные расхождения – это ошибки при заполнении форм или разные подходы к тому, что считать денежными эквивалентами. Прежде чем строить выводы на денежных потоках, стоит проверить, к каким компаниям относятся расхождения.</p>
<p><strong>Прибыль и деньги.</strong> Чистая прибыль – это не деньги. Прибыль отражает доходы и расходы в момент их признания, а денежный поток – в момент оплаты. Компания может показывать прибыль, но не получать денег: например, если покупатели платят с большой отсрочкой или деньги оседают в запасах.</p>
<div class="cell" data-layout-align="center">
<details open="" class="code-fold"><summary>Код</summary><div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb17"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a>flows <span class="op">=</span> d.groupby(<span class="st">"div"</span>).<span class="bu">apply</span>(<span class="kw">lambda</span> g: pd.Series({</span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a>    <span class="st">"доля с прибылью"</span>: (g[<span class="st">"line_2400"</span>] <span class="op">&gt;</span> <span class="dv">0</span>).mean(),</span>
<span id="cb17-3"><a href="#cb17-3" aria-hidden="true" tabindex="-1"></a>    <span class="st">"доля с положительным CFO"</span>: (g[<span class="st">"line_4100"</span>] <span class="op">&gt;</span> <span class="dv">0</span>).mean(),</span>
<span id="cb17-4"><a href="#cb17-4" aria-hidden="true" tabindex="-1"></a>}), include_groups<span class="op">=</span><span class="va">False</span>).<span class="bu">round</span>(<span class="dv">2</span>)</span>
<span id="cb17-5"><a href="#cb17-5" aria-hidden="true" tabindex="-1"></a>flows</span>
<span id="cb17-6"><a href="#cb17-6" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;      доля с прибылью  доля с положительным CFO</span></span>
<span id="cb17-7"><a href="#cb17-7" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; div                                           </span></span>
<span id="cb17-8"><a href="#cb17-8" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; 10              0.82                      0.64</span></span>
<span id="cb17-9"><a href="#cb17-9" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; 41              0.78                      0.41</span></span>
<span id="cb17-10"><a href="#cb17-10" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; 47              0.77                      0.49</span></span>
<span id="cb17-11"><a href="#cb17-11" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; 49              0.73                      0.56</span></span>
<span id="cb17-12"><a href="#cb17-12" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; 62              0.81                      0.61</span></span></code></pre></div><button title="Скопировать текст" class="code-copy-button"><i class="bi"></i></button></div>
</details>
</div>
<p>Разница особенно велика в строительстве: прибыль показывают 78% компаний, а положительный денежный поток от текущих операций – только 41%. Застройщик годами вкладывает деньги в строительство, а выручку и прибыль признаёт при сдаче объекта. Кроме того, с 2019 г. деньги покупателей жилья поступают не застройщику, а на эскроу-счета в банке и раскрываются только после ввода дома. Сравнение прибыли с денежным потоком – один из главных инструментов проверки «качества прибыли», к нему мы вернёмся при анализе кредитного риска.</p>
</section><section id="итоги" class="level2 unnumbered"><h2 class="unnumbered anchored" data-anchor-id="итоги">Итоги</h2>
<ul>
<li>Бухгалтерская отчётность (РСБУ) всех российских организаций публикуется ФНС; набор RFSD собирает и очищает её с 2011 г. – около 2 млн отчётов в год.</li>
<li>Отчётность описывает отдельное юрлицо, а не группу: выручка холдинга может быть в тысячи раз меньше выручки операционной компании.</li>
<li>В RFSD строки форм – это столбцы с кодами; единицы – тысячи рублей; расходы («строки в скобках») хранятся отрицательными. Формулы зависят от версии данных.</li>
<li>Для больших таблиц удобен Polars: ленивые вычисления читают только нужные столбцы и строки, в том числе прямо с сервера.</li>
<li>Компании отрасли отбираются по основному коду ОКВЭД; правило отбора нужно явно описать.</li>
<li>Качество данных: проверка баланса, флаги RFSD, отрицательный капитал, скрытая отчётность, новые формы с 2025 г.</li>
<li>Около пятой части крупных компаний, а по выручке – около трети, не раскрывают отчётность; среди них крупнейшие компании страны. Отраслевые выводы по RFSD описывают компании, раскрывшие отчётность.</li>
<li>В RFSD нет названий компаний: данные связывают по ИНН, названия берут из ГИР БО, ЕГРЮЛ или раскрытия эмитентов.</li>
<li>Распределения коэффициентов имеют тяжёлые хвосты – для сравнений используют медианы и квантили.</li>
<li>Формы отчётности связаны: сверка денег в балансе и отчёте о движении денежных средств, сравнение прибыли и денежного потока.</li>
</ul></section><section id="sec-exercises-rfsd" class="level2" data-number="5.8"><h2 data-number="5.8" class="anchored" data-anchor-id="sec-exercises-rfsd">
<span class="header-section-number">5.8</span> Упражнения</h2>
<section id="а.-понимание" class="level3" data-number="5.8.1"><h3 data-number="5.8.1" class="anchored" data-anchor-id="а.-понимание">
<span class="header-section-number">5.8.1</span> А. Понимание</h3>
<ol type="1">
<li>Почему у холдинговой компании чистая прибыль может быть больше выручки? В какой строке отчёта о финансовых результатах это видно?</li>
<li>В RFSD <code>line_2110 = 500 000</code>, <code>line_2120 = −380 000</code>. Чему равна валовая прибыль в рублях? Что было бы, если бы вы посчитали её как <code>line_2110 − line_2120</code>?</li>
<li>У компании капитал 1 млн руб., чистая прибыль 3 млн руб. Чему равна ROE? Что эта цифра говорит о компании, а что – нет?</li>
<li>Почему для сравнения рентабельности компаний отрасли используют медиану, а не среднее?</li>
</ol></section><section id="б.-практика-на-своей-отрасли" class="level3" data-number="5.8.2"><h3 data-number="5.8.2" class="anchored" data-anchor-id="б.-практика-на-своей-отрасли">
<span class="header-section-number">5.8.2</span> Б. Практика на своей отрасли</h3>
<ol start="5" type="1">
<li>Загрузите из полного RFSD (Hugging Face) отчётность компаний своей отрасли (код ОКВЭД назначает преподаватель) за 2025 г. Сколько компаний подали отчётность? Сколько из них с выручкой больше 100 млн руб.?</li>
<li>Для своей отрасли проверьте: у какой доли компаний не сходится баланс, отрицательный капитал, скрытая отчётность (компании, которые отчитывались в 2023 г., но не в 2025 г.)?</li>
<li>Посчитайте медианы и квартили коэффициентов из таблицы <a href="#tbl-ratios" class="quarto-xref"><span>5.2</span></a> для своей отрасли. Сравните с классами выборки книги.</li>
</ol></section><section id="в.-работа-с-ии-ассистентом" class="level3" data-number="5.8.3"><h3 data-number="5.8.3" class="anchored" data-anchor-id="в.-работа-с-ии-ассистентом">
<span class="header-section-number">5.8.3</span> В. Работа с ИИ-ассистентом</h3>
<ol start="8" type="1">
<li>Попросите ИИ-ассистента написать функцию расчёта EBIT и коэффициента покрытия процентов по данным RFSD. Проверьте на отчётности «Тандера» из <code>data.load_rfsd_cases()</code>: учёл ли ассистент, что проценты к уплате в RFSD отрицательны? Какой результат получился бы без учёта знака?</li>
<li>Спросите ассистента, какова выручка «Магнита» за 2023 г. Сравните ответ с данными RFSD по ПАО «Магнит» и АО «Тандер». Какую отчётность – РСБУ или МСФО, какого юрлица – подразумевал ассистент?</li>
</ol></section><section id="г.-мини-исследование" class="level3" data-number="5.8.4"><h3 data-number="5.8.4" class="anchored" data-anchor-id="г.-мини-исследование">
<span class="header-section-number">5.8.4</span> Г. Мини-исследование</h3>
<ol start="10" type="1">
<li><p>Какая доля компаний вашей отрасли, отчитывавшихся в 2021 г., перестала раскрывать отчётность к 2025 г.? Отличаются ли они (по выручке и рентабельности 2021 г.) от тех, кто продолжил отчитываться? Какие выводы об отрасли по данным 2025 г. из-за этого могут быть смещены? Подготовьте короткий устный рассказ.</p></li>
<li><p>Сравните охват RFSD со статистикой Росстата для своей отрасли за 2018–2025 гг. (ряды – в rustata, набор <code>showdata/indicator_278140</code>, выручка по более детальным кодам ОКВЭД). Как менялся охват? Каких крупных компаний не хватает в RFSD и когда они перестали раскрывать отчётность? Как это влияет на выводы о рентабельности и концентрации отрасли?</p></li>
</ol></section></section><section id="вопросы-для-самопроверки" class="level2 unnumbered"><h2 class="unnumbered anchored" data-anchor-id="вопросы-для-самопроверки">Вопросы для самопроверки</h2>
<ol type="1">
<li>Чем отчётность по РСБУ отличается от консолидированной отчётности группы по МСФО?</li>
<li>В каких единицах записаны денежные показатели в RFSD и с каким знаком хранятся расходы?</li>
<li>Что делает метод <code>collect()</code> в Polars и почему ленивые вычисления ускоряют работу с большими файлами?</li>
<li>Какие проверки качества отчётности вы знаете?</li>
<li>Почему прибыль компании может быть положительной, а денежный поток от текущих операций – отрицательным?</li>
<li>Почему по данным RFSD нельзя посчитать EBITDA и что использовать вместо неё?</li>
</ol>
<div class="callout callout-style-simple callout-tip callout-titled" title="Ответы">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-6-contents" aria-controls="callout-6" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Совет</span>Ответы
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-6" class="callout-6-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<ol type="1">
<li>РСБУ – отчётность отдельного юрлица по российским стандартам; МСФО – консолидированная отчётность группы по международным стандартам, где внутригрупповые обороты исключаются.</li>
<li>В тысячах рублей; строки, которые в формах пишутся в скобках (расходы, выбытия), – отрицательными числами.</li>
<li>Запускает выполнение построенного плана запроса. Ленивые вычисления позволяют оптимизировать план: читать только нужные столбцы, применять фильтры при чтении, не создавать промежуточных таблиц.</li>
<li>Равенство активов и пассивов; суммы разделов; совпадение денег в балансе и отчёте о движении денежных средств; флаги RFSD (<code>filed</code>, <code>imputed</code>, <code>outlier</code>); неположительный капитал.</li>
<li>Прибыль признаётся в момент продажи, а деньги поступают при оплате: отсрочка платежа покупателям, рост запасов, специфика отрасли (например, строительство с эскроу-счетами).</li>
<li>В RFSD нет амортизации: в форме 2 она входит в себестоимость и другие расходы, отчёт о движении денежных средств по РСБУ составляется прямым методом, а пояснения (строка 5640) в базу не входят. Вместо EBITDA используют EBIT или прибыль от продаж под их настоящими названиями, а EBITDA публичных компаний берут из отчётности по МСФО.</li>
</ol>
</div>
</div>
</div>
</section><section id="что-почитать" class="level2 unnumbered page-columns page-full"><h2 class="unnumbered anchored" data-anchor-id="что-почитать">Что почитать</h2>
<ul>
<li>
<span class="citation" data-cites="bondarkov2025">Bondarkov и др. (<a href="references.html#ref-bondarkov2025" role="doc-biblioref">2025 г.</a>)</span> – описание набора данных RFSD: источники, методы очистки, ограничения.</li>
<li>
<span class="citation" data-cites="tidyfinance2024">Scheuch и др. (<a href="references.html#ref-tidyfinance2024" role="doc-biblioref">2024 г.</a>)</span>, раздел о работе с базами данных – организация больших финансовых данных в исследовательском проекте.</li>
</ul>


<div class="no-row-height column-margin column-container"><div id="ref-bondarkov2025" class="csl-entry" role="listitem">
Bondarkov, Sergey, Victor Ledenev, и Dmitriy Skougarevskiy. 2025 г. <span>«Russian Financial Statements Database»</span>. <em>Scientific Data</em> 12. <a href="https://doi.org/10.1038/s41597-025-05150-1">https://doi.org/10.1038/s41597-025-05150-1</a>.
</div><div id="ref-tidyfinance2024" class="csl-entry" role="listitem">
Scheuch, Christoph, Stefan Voigt, Patrick Weiss, и Christoph Frey. 2024 г. <em>Tidy Finance with <span>Python</span></em>. Chapman; Hall/CRC. <a href="https://www.tidy-finance.org">https://www.tidy-finance.org</a>.
</div></div>
</section></main><!-- /main --><script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Скопировано");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Скопировано");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script><nav class="page-navigation"><div class="nav-page nav-page-previous">
      <a href="./04-returns-risk.html" class="pagination-link" aria-label="Доходность и риск">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Доходность и риск</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./06-industry-analysis.html" class="pagination-link" aria-label="Отраслевой анализ">
        <span class="nav-page-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Отраслевой анализ</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->



<script src="site_libs/quarto-html/zenscroll-min.js"></script>
</body></html>