project:
  type: book

book:
  title: "Количественные финансы"
  author: "Марсель Салихов"
  language: ru
  date: 2025-08-30
  chapters:
    - index.qmd
    - 01-intro.qmd
    - part: "Финансовые данные и х обработка"    # название раздела
      chapters:
      - 02-financial-data.qmd
      - 02-financial-data-russia.qmd

    # Добавьте здесь другие главы по мере написания:
    # - 02-financial-data.qmd
    # - 03-var-es.qmd
    # - 04-capm.qmd
    # - 05-bond-pricing.qmd
    # и т.д.

bibliography: references.bib

format:
  html:
    lang: ru
    theme: lumen
    code-fold: true
    code-tools: false
    toc: true
    number-depth: 2
    number-sections: true
  pdf:
    pdf-engine: typst
    lang: ru
    papersize: a4
    default-image-extension: png
    fig-format: png
  docx: default

execute:
  freeze: auto  # чтобы избежать лишней переработки при рендеринге
  echo: true
