{
  "hash": "b046fdf0160966be6ecdf5e4c214e580",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Отраслевой анализ\"\n---\n\n<!--\nМатериалы: ноутбук Russian_corporate_data_RFSD_2025_charting (DuPont, «гипербола ROA», Лоренц);\nкритерии и лучшие работы проекта 1 (org/project-1).\nИдеи из курса Рыбина (2025; только идеи): отраслевые профили отчётности (Модуль3_3, с. 5–14).\n-->\n\n\n\n\n\nВ 2025 г. две крупнейшие продуктовые сети страны продали товаров на сопоставимые суммы: выручка ООО «Агроторг» (ИНН 7825706086), которому принадлежат магазины «Пятёрочка», составила 3,44 трлн руб., АО «Тандер» (ИНН 2310031475), которое управляет магазинами «Магнит», – 3,05 трлн руб. «Агроторг» заработал 23,9 млрд руб. чистой прибыли, а «Тандер» получил убыток 22,5 млрд. Рентабельность продаж первого – 0,7%, второго – −0,7%: меньше копейки прибыли или убытка с рубля выручки.\n\nА теперь посмотрим на рентабельность капитала – доход собственников на вложенный ими капитал. У «Тандера» она отрицательна: −16%. А у «Агроторга» – 82%, больше, чем у большинства компаний-разработчиков программ, которые зарабатывают с рубля выручки в разы больше. Как сеть, у которой с рубля выручки остаётся меньше копейки, может приносить собственникам 82% в год? Ответ даёт разложение DuPont, с которого начинается эта глава. Затем мы научимся описывать отрасль целиком: какова «типичная» компания, насколько сосредоточен рынок, чем лидеры отличаются от остальных и как устроены балансы компаний разных отраслей.\n\n::: {.callout-note title=\"В этой главе\"}\n- Раскладываем рентабельность капитала на маржу, оборачиваемость и финансовый рычаг (DuPont).\n- Строим «гиперболу ROA» – карту бизнес-моделей отрасли.\n- Измеряем концентрацию отрасли: доля крупнейших компаний, индекс Херфиндаля – Хиршмана, кривая Лоренца.\n- Сравниваем лидеров отрасли с остальными и проверяем гипотезу статистически.\n- Следим за динамикой показателей и не путаем изменения компаний с изменением состава выборки.\n- Сравниваем структуру балансов разных отраслей.\n\n**Данные:** `rfsd_sample.parquet` – выборка RFSD из предыдущей главы.\n**Нужно знать:** формы отчётности и финансовые коэффициенты (глава «Большие данные корпоративной отчётности»).\n:::\n\n## Разложение DuPont {#sec-dupont}\n\n### Три источника рентабельности\n\nРентабельность капитала (ROE) – отношение чистой прибыли к капиталу собственников. Умножим и разделим её на выручку и на активы:\n\n$$\n\\text{ROE} = \\frac{\\text{Прибыль}}{\\text{Капитал}}\n= \\underbrace{\\frac{\\text{Прибыль}}{\\text{Выручка}}}_{\\text{маржа (ROS)}} \\times\n  \\underbrace{\\frac{\\text{Выручка}}{\\text{Активы}}}_{\\text{оборачиваемость}} \\times\n  \\underbrace{\\frac{\\text{Активы}}{\\text{Капитал}}}_{\\text{мультипликатор}}.\n$$ {#eq-dupont}\n\nЭто тождество – **разложение DuPont** (по названию химической компании DuPont, где его стали использовать ещё в начале XX в.). Оно показывает, что акционер может зарабатывать тремя способами:\n\n- **маржой** – получать много прибыли с каждого рубля продаж;\n- **оборачиваемостью** – быстро «прокручивать» активы, продавая на каждый рубль активов много товаров;\n- **финансовым рычагом** – финансировать активы в большей степени за счёт долга, а не собственного капитала.\n\nПроизведение первых двух множителей – рентабельность активов: $\\text{ROA} = \\text{ROS} \\times \\text{оборачиваемость}$. Третий множитель показывает, во сколько раз рычаг «увеличивает» ROA до ROE. Рычаг работает в обе стороны: при убытках он так же увеличивает потери капитала, поэтому высокий ROE за счёт мультипликатора – это не только эффективность, но и риск.\n\n### Две сети\n\nПрименим разложение к «Тандеру» и «Агроторгу» за три последних года.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.python .cell-code}\ncols = [\"ros\", \"turnover\", \"multiplier\", \"roa\", \"roe\"]\ndupont = pairs.loc[pairs.index.get_level_values(\"year\") >= YEAR - 2, cols]\ndupont.round(3)\n#>                    ros  turnover  multiplier    roa    roe\n#> inn        year                                           \n#> 2310031475 2023  0.028     1.742       7.628  0.049  0.372\n#>            2024  0.017     2.001       8.352  0.034  0.287\n#>            2025 -0.007     1.847      11.882 -0.014 -0.162\n#> 7825706086 2023  0.015     2.286      12.834  0.034  0.439\n#>            2024  0.014     2.351      14.961  0.034  0.506\n#>            2025  0.007     2.729      43.152  0.019  0.818\n```\n:::\n\n\nВ 2023 г. обе сети были прибыльны, и разница между ними была умеренной: маржа «Тандера» – 2,8%, «Агроторга» – 1,5%; мультипликатор капитала – 7,6 и 12,8. «Агроторг» зарабатывал с рубля выручки меньше, но за счёт большего рычага его ROE (44%) была выше, чем у «Тандера» (37%).\n\nК 2025 г. маржа обеих сетей снизилась, а у «Тандера» стала отрицательной. Рентабельность активов «Агроторга» – всего 1,9%. Но мультипликатор капитала вырос до 43: активы компании в 43 раза больше её собственного капитала. Капитал сократился с 83,0 млрд руб. на конец 2024 г. до 29,2 млрд на конец 2025 г., хотя за год компания получила прибыль. Так бывает, когда собственникам распределяют больше, чем компания заработала, например выплачивают дивиденды за прошлые годы. Именно рычаг превращает рентабельность активов в 1,9% в рентабельность капитала в 82%. У «Тандера» тот же механизм работает в обратную сторону: при мультипликаторе 11,9 небольшой убыток относительно выручки превращается в ощутимую потерю капитала.\n\nОтсюда важный вывод для анализа: сравнивать компании по одному показателю рентабельности недостаточно. Нужно понимать, из чего он складывается. И помнить, что отчётность юрлица по РСБУ отражает его место внутри группы: сколько капитала оставлено в операционной компании, а сколько выведено в виде дивидендов материнской компании, – это во многом решение собственников, а не результат работы магазинов. Высокая ROE «Агроторга» говорит скорее о финансовой политике группы, чем о выдающейся эффективности магазинов.\n\n### Гипербола ROA\n\nРазложение DuPont удобно изобразить на графике. Отложим по горизонтали оборачиваемость активов, по вертикали – маржу. Тогда компании с одинаковой рентабельностью активов лежат на гиперболе $\\text{ROS} = \\text{ROA} / \\text{оборачиваемость}$.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.python .cell-code}\nd = r[(r[\"year\"] == YEAR) & r[\"ros\"].between(-0.2, 0.4) & r[\"turnover\"].between(0.05, 20)]\ncolors = dict(zip(DIV, [plot.BLUE, plot.ORANGE, plot.GREEN, plot.RED, plot.NAVY]))\n\nfig, ax = plt.subplots(figsize=(6.5, 3.8))\nfor code in DIV:\n    g = d[d[\"div\"] == code]\n    ax.scatter(g[\"turnover\"], g[\"ros\"], s=3, alpha=0.2, color=colors[code], lw=0)\n    ax.scatter(g[\"turnover\"].median(), g[\"ros\"].median(), s=60, color=colors[code],\n               edgecolor=\"white\", lw=1, zorder=3, label=DIV[code])\nx = np.logspace(np.log10(0.05), np.log10(20), 200)\nfor roa in (0.02, 0.05, 0.10, 0.20):\n    ax.plot(x, roa / x, color=\"#6B7280\", lw=0.8, ls=\"--\")\n    ax.annotate(f\"ROA {roa:.0%}\", (roa / 0.4, 0.4), fontsize=7, color=\"#6B7280\",\n                xytext=(2, -8), textcoords=\"offset points\")\nax.set_xscale(\"log\")\nax.set_xticks([0.1, 0.3, 1, 3, 10])\nax.xaxis.set_major_formatter(plt.FuncFormatter(lambda v, _: f\"{v:g}\".replace(\".\", \",\")))\nax.axhline(0, color=\"#9CA3AF\", lw=0.6)\nax.set_ylim(-0.2, 0.4)\nax.set_xlabel(\"Оборачиваемость активов (выручка / активы), логарифмическая шкала\")\nax.set_ylabel(\"Рентабельность продаж\")\nax.yaxis.set_major_formatter(plt.FuncFormatter(lambda y, _: f\"{y:.0%}\"))\nax.legend(title=\"Медиана отрасли\", loc=\"lower left\", fontsize=7, title_fontsize=7)\nplot.source(ax, \"RFSD, расчёты автора\", offset=32)\nplt.show()\n```\n\n::: {.cell-output-display}\n![Маржа и оборачиваемость активов компаний выборки в 2025 г. Крупные точки – медианы отраслей, пунктир – линии одинаковой ROA](06-industry-analysis_files/figure-html/fig-roa-hyperbola-1.svg){#fig-roa-hyperbola fig-align='center'}\n:::\n:::\n\n\n\n\nОтрасли занимают на графике разные области. Разработчики программного обеспечения – наверху: медианная маржа 5,5% при умеренной оборачиваемости. Розничная торговля – справа внизу: маржа всего 1,1%, но активы оборачиваются 2,6 раза в год. Одна и та же рентабельность активов может достигаться очень разными бизнес-моделями, и сравнивать маржу розничной сети с маржой ИТ-компании бессмысленно.\n\n::: {.panel-tabset}\n\n### Python\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.python .cell-code}\nmed.round(3)\n#>        ros  turnover  multiplier    roa    roe\n#> div                                           \n#> 10   0.017     1.950       2.547  0.038  0.154\n#> 41   0.011     1.091       7.214  0.011  0.186\n#> 47   0.011     2.562       3.812  0.028  0.183\n#> 49   0.008     1.454       3.676  0.014  0.122\n#> 62   0.055     1.539       2.146  0.084  0.281\n```\n:::\n\n\n### R\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nlibrary(dplyr)\npos <- function(x) ifelse(x > 0, x, NA)\nqf_load_rfsd(years = 2025) |>\n  filter(filed == 1) |>\n  mutate(div = substr(okved, 1, 2),\n         ros = line_2400 / pos(line_2110),\n         turnover = line_2110 / pos(line_1600),\n         multiplier = line_1600 / pos(line_1300),\n         roa = line_2400 / pos(line_1600),\n         roe = line_2400 / pos(line_1300)) |>\n  group_by(div) |>\n  summarise(across(ros:roe, \\(x) round(median(x, na.rm = TRUE), 3)))\n#> # A tibble: 5 x 6\n#>   div     ros turnover multiplier   roa   roe\n#>   <chr> <dbl>    <dbl>      <dbl> <dbl> <dbl>\n#> 1 10    0.017     1.95       2.55 0.038 0.154\n#> 2 41    0.011     1.09       7.21 0.011 0.186\n#> 3 47    0.011     2.56       3.81 0.028 0.183\n#> 4 49    0.008     1.45       3.68 0.014 0.122\n#> 5 62    0.055     1.54       2.15 0.084 0.281\n```\n:::\n\n\n:::\n\nТаблица показывает ещё одну особенность: в строительстве медианный мультипликатор капитала – 7,2. Застройщики финансируют стройку в основном заёмными средствами, прежде всего проектным кредитованием банков, поэтому даже при очень низкой рентабельности активов (1,1%) их ROE сопоставима с другими отраслями.\n\n### Рычаг: ROA падает, ROE – нет\n\nРазложение DuPont подсказывает, что долг «увеличивает» рентабельность капитала. Посмотрим, как это выглядит на всех компаниях выборки: разобьём их на группы по доле обязательств в активах и посчитаем медианы.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.python .cell-code}\nd = r[r[\"year\"] == YEAR].copy()\nd[\"обязательства / активы\"] = (d[\"line_1400\"] + d[\"line_1500\"]) / pos(d[\"line_1600\"])\nd = d[d[\"обязательства / активы\"].between(0, 1.5)]\nd[\"группа\"] = pd.cut(d[\"обязательства / активы\"], [0, 0.2, 0.4, 0.6, 0.8, 0.9, 1.0, 1.5])\nlev = d.groupby(\"группа\", observed=True).agg(\n    компаний=(\"inn\", \"size\"), roa=(\"roa\", \"median\"), roe=(\"roe\", \"median\"),\n    доля_убыточных=(\"line_2400\", lambda x: (x < 0).mean()))\nlev.round(3)\n#>             компаний    roa    roe  доля_убыточных\n#> группа                                            \n#> (0.0, 0.2]       727  0.095  0.108           0.193\n#> (0.2, 0.4]       965  0.106  0.157           0.113\n#> (0.4, 0.6]      1285  0.080  0.166           0.100\n#> (0.6, 0.8]      1857  0.048  0.164           0.113\n#> (0.8, 0.9]      1360  0.023  0.160           0.132\n#> (0.9, 1.0]      2316  0.007  0.265           0.142\n#> (1.0, 1.5]       764 -0.034    NaN           0.733\n```\n:::\n\n\n\n\nДве медианы ведут себя по-разному. У компаний, у которых обязательства составляют 20–40% активов, медианная ROA – 10,6%, у компаний с долей обязательств 90–100% – 0,7%. Ранговая корреляция доли обязательств и ROA равна −0,47. А медианная ROE не падает вслед за ROA: в группе 20–40% она равна 16%, а в группе 90–100% – 27%.\n\nКак это понимать? Во-первых, связь между долгом и ROA работает в обе стороны. Компания может брать в долг, потому что активно растёт, но чаще высокая доля обязательств – следствие проблем: убытки «съедают» капитал, и компания живёт за счёт кредиторов, в том числе поставщиков и связанных лиц. Прибыльные компании, наоборот, накапливают капитал и меньше нуждаются в займах. Во-вторых, высокая ROE в правой части таблицы во многом механическая: когда капитал мал, даже небольшая прибыль даёт высокое отношение. В-третьих, у 8% компаний капитал отрицательный (последняя группа), ROE для них не определена, и они выпадают из расчёта, хотя 73% из них убыточны. Высокая медианная ROE закредитованных компаний – отчасти результат того, что самые проблемные из них в расчёт не попали.\n\nВывод для анализа: высокая ROE при большом мультипликаторе капитала – повод посмотреть на баланс внимательнее, а не признак успеха.\n\n::: {.callout-note title=\"Почему не EBITDA\"}\nВ отраслевых обзорах маржу и долговую нагрузку часто сравнивают по EBITDA. По данным RFSD этого сделать нельзя: в российской отчётности нет строки с амортизацией (см. раздел [-@sec-no-ebitda]). Для капиталоёмких отраслей – транспорта, энергетики, добычи – разница между EBIT и EBITDA особенно велика, поэтому сравнивать их с малокапиталоёмкими отраслями по EBIT нужно с оговоркой: часть различий в марже объясняется амортизацией, а не эффективностью.\n:::\n\n## Концентрация отрасли {#sec-concentration}\n\nНасколько рынок поделен между немногими крупными игроками? Это важно и для инвестора (в концентрированных отраслях лидеры обычно устойчивее и прибыльнее), и для регулятора (высокая концентрация может означать недостаток конкуренции). Три стандартные меры концентрации:\n\n- **доля крупнейших компаний** – например, CR5, доля пяти крупнейших компаний в суммарной выручке;\n- **индекс Херфиндаля – Хиршмана (HHI)** – сумма квадратов рыночных долей в процентах: $\\text{HHI} = \\sum_i s_i^2$. Он равен 10 000 при монополии и близок к нулю на раздробленном рынке. В методике ФАС России рынок с HHI от 1 000 до 2 000 считается умеренно концентрированным, выше 2 000 – высококонцентрированным;\n- **коэффициент Джини** и кривая Лоренца – насколько неравномерно выручка распределена между компаниями.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.python .cell-code}\ntrapz = getattr(np, \"trapezoid\", None) or np.trapz\n\ndef concentration(g):\n    x = np.sort(g[\"line_2110\"].dropna().to_numpy())\n    share = x / x.sum()\n    lorenz = np.concatenate([[0], np.cumsum(x) / x.sum()])\n    gini = 1 - 2 * trapz(lorenz, np.linspace(0, 1, len(lorenz)))\n    return pd.Series({\"компаний\": len(x), \"CR5\": share[::-1][:5].sum(),\n                      \"HHI\": (share ** 2).sum() * 1e4, \"Джини\": gini})\n\nconc = r[r[\"year\"] == YEAR].groupby(\"div\").apply(concentration, include_groups=False)\nconc.round(3)\n#>      компаний    CR5      HHI  Джини\n#> div                                 \n#> 10     2141.0  0.060   24.158  0.614\n#> 41     3687.0  0.060   20.345  0.645\n#> 47     2098.0  0.338  338.938  0.866\n#> 49     1319.0  0.190  128.548  0.771\n#> 62     1102.0  0.129   67.252  0.641\n```\n:::\n\n\n\n\nРозничная торговля – самая концентрированная из пяти отраслей: на пять крупнейших компаний приходится 34% выручки, HHI – 339. Производство пищевых продуктов и строительство, напротив, раздроблены: CR5 – 6% и 6%.\n\nА вот цифру для разработчиков программ стоит проверить, прежде чем её интерпретировать. В 2024 г. CR5 в классе 62 был 23%, в 2025 г. – 13%. Неужели за год рынок стал почти вдвое менее концентрированным? Нет: крупнейшая компания класса, ООО «Яндекс» (ИНН 7736207543) с выручкой 545 млрд руб. в 2024 г., за 2025 г. отчётность не раскрыла (`filed = 0`), и ещё несколько крупных компаний выпали из данных. Концентрация «снизилась» не из-за конкуренции, а из-за того, что лидеры пропали из выборки.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.python .cell-code}\nfig, ax = plt.subplots(figsize=(4.8, 4))\nfor code, color in [(\"47\", \"#3F8F5B\"), (\"62\", \"#23415F\"), (\"41\", \"#C8702A\")]:\n    x = np.sort(r[(r[\"year\"] == YEAR) & (r[\"div\"] == code)][\"line_2110\"].dropna().to_numpy())\n    lorenz = np.concatenate([[0], np.cumsum(x) / x.sum()])\n    ax.plot(np.linspace(0, 1, len(lorenz)), lorenz, color=color, label=DIV[code])\nax.plot([0, 1], [0, 1], color=\"#6B7280\", ls=\":\", lw=0.8, label=\"равномерное распределение\")\nax.set_xlabel(\"Доля компаний (от меньших к большим)\")\nax.set_ylabel(\"Доля выручки\")\nax.xaxis.set_major_formatter(plt.FuncFormatter(lambda v, _: f\"{v:.0%}\"))\nax.yaxis.set_major_formatter(plt.FuncFormatter(lambda v, _: f\"{v:.0%}\"))\nax.legend(fontsize=7)\nplot.source(ax, \"RFSD, расчёты автора\", offset=32)\nplt.show()\n```\n\n::: {.cell-output-display}\n![Кривые Лоренца для выручки компаний в 2025 г.](06-industry-analysis_files/figure-html/fig-lorenz-1.svg){#fig-lorenz fig-align='center'}\n:::\n:::\n\n\n::: {.callout-warning title=\"Типичная ошибка\"}\nСчитать концентрацию по неполному списку компаний. Наша выборка содержит только компании с выручкой от 1 млрд руб. хотя бы в одном году, поэтому показатели выше описывают концентрацию **среди крупных компаний**. Если добавить тысячи мелких фирм, доля пяти крупнейших снизится, а коэффициент Джини вырастет – насколько, зависит от отрасли. Кроме того, компании, скрывшие отчётность (глава «Большие данные корпоративной отчётности»), выпадают из расчёта: концентрация получается заниженной, если среди них есть крупные игроки, – как в примере с ИТ-компаниями выше. Прежде чем интерпретировать резкое изменение концентрации, проверьте, не пропали ли из данных лидеры прошлого года. Всегда указывайте, по какому кругу компаний посчитан показатель.\n:::\n\n## Лидеры и остальные {#sec-leaders}\n\nПравда ли, что крупнейшие компании отрасли эффективнее остальных? И если да, то за счёт чего – маржи, оборачиваемости или рычага? Это типичный вопрос отраслевого анализа, и отвечать на него нужно так же, как на любой исследовательский вопрос: сформулировать гипотезу, выбрать показатели и проверить гипотезу на данных.\n\nРазделим компании каждой отрасли в 2025 г. на лидеров (10% крупнейших по выручке) и остальных и сравним медианы.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.python .cell-code}\nd23 = r[r[\"year\"] == YEAR].copy()\nd23[\"лидер\"] = d23.groupby(\"div\")[\"line_2110\"].transform(lambda x: x >= x.quantile(0.9))\ncomp = d23.groupby([\"div\", \"лидер\"])[[\"ros\", \"turnover\", \"multiplier\", \"roa\"]].median().round(3)\ncomp\n#>              ros  turnover  multiplier    roa\n#> div лидер                                    \n#> 10  False  0.017     2.000       2.542  0.036\n#>     True   0.028     1.647       2.669  0.058\n#> 41  False  0.010     1.055       6.857  0.009\n#>     True   0.014     1.364      11.224  0.022\n#> 47  False  0.010     2.564       3.691  0.026\n#>     True   0.022     2.492       5.256  0.050\n#> 49  False  0.008     1.469       3.761  0.014\n#>     True   0.012     1.186       2.414  0.017\n#> 62  False  0.058     1.498       2.049  0.087\n#>     True   0.026     1.726       3.339  0.074\n```\n:::\n\n\n\n\nВ розничной торговле разница заметна: медианная ROA лидеров – 5,0%, остальных – 2,6%. Оборачиваемость активов у лидеров и остальных почти одинакова (2,49 и 2,56), а разница создаётся маржой: 2,2% против 1,0%. Крупные сети, по-видимому, выигрывают на масштабе закупок, логистике и переговорной силе с поставщиками. Заметьте и ещё одно отличие: мультипликатор капитала у лидеров выше (5,3 против 3,7), то есть они активнее используют заёмные средства.\n\nНе случайна ли эта разница? Распределения рентабельности далеки от нормального, поэтому вместо $t$-теста для сравнения двух групп используем непараметрический **критерий Манна – Уитни**: он проверяет, склонны ли значения одной группы быть больше значений другой, и не чувствителен к выбросам.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.python .cell-code}\nstats.mannwhitneyu(lead, rest, alternative=\"two-sided\")\n#> MannwhitneyuResult(statistic=234456.0, pvalue=7.3151914408634156e-06)\n```\n:::\n\n\np-значение меньше 0,001 при 210 лидерах и 1 941 остальных компаниях: разница статистически значима.\n\nПроверим ту же гипотезу для производства пищевых продуктов. Медианная ROA лидеров – 5,8%, остальных – 3,6%, но p-значение 0,07: на уровне 5% разница незначима. При этом по данным за 2023 г. та же проверка давала p-значение меньше 0,001 (ROA лидеров 11,3% против 5,3%). Вывод «лидеры эффективнее» оказывается неустойчивым: он зависит от отрасли и года. Поэтому хороший отраслевой анализ проверяет вывод на нескольких годах, а не на одном удачном.\n\nНаконец, статистическая значимость не отвечает на вопрос «почему». Лидеры могут быть эффективнее, потому что они крупные (эффект масштаба), а могут быть крупными, потому что эффективнее (успешные компании растут). По данным одного года эти объяснения не различить – для этого нужны данные за много лет и более сложные методы.\n\n## Динамика и состав выборки {#sec-dynamics}\n\nКак менялась рентабельность отраслей в 2018–2025 гг.?\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.python .cell-code}\ndyn = r.groupby([\"year\", \"div\"])[\"ros\"].median().unstack()\nax = dyn.rename(columns=DIV).plot(marker=\"o\", rot=0)\nax.set_xlabel(\"\")\nax.yaxis.set_major_formatter(plt.FuncFormatter(lambda y, _: f\"{y:.0%}\"))\nax.legend(fontsize=7, ncol=2)\nplot.source(ax, \"RFSD, расчёты автора\")\nplt.show()\n```\n\n::: {.cell-output-display}\n![Медианная рентабельность продаж по отраслям](06-industry-analysis_files/figure-html/fig-ros-dynamics-3.svg){#fig-ros-dynamics fig-align='center'}\n:::\n:::\n\n\n\n\nБросаются в глаза две вещи. Первая – рост рентабельности разработчиков программного обеспечения: с 4,3% в 2018 г. до 7,8% в 2023 г. Среди вероятных причин – уход с российского рынка иностранных поставщиков программ после 2022 г. и налоговые льготы для ИТ-компаний. Вторая – снижение рентабельности во всех пяти отраслях в 2025 г. У ИТ-компаний медианная маржа вернулась к 5,5%, а доля убыточных среди крупных компаний выросла: в 2024 г. она была от 14% до 20% в зависимости от отрасли, в 2025 г. – от 17% до 25%. Объяснять эти изменения экономикой – санкциями, спросом, ставками – можно, но только после того, как исключено более простое объяснение: изменение **состава выборки**.\n\nМедиана за каждый год считается по тем компаниям, которые отчитались в этом году. Если в отрасль пришли новые, более рентабельные компании, медиана вырастет, даже если ни одна из прежних компаний не стала эффективнее. Бывает и наоборот: если сильные компании перестали раскрывать отчётность, медиана упадёт. Проверим это на **сбалансированной панели** – только тех ИТ-компаниях, которые отчитывались во все годы периода.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.python .cell-code}\nit = r[r[\"div\"] == \"62\"]\nyears_present = it.groupby(\"inn\")[\"year\"].nunique()\nbalanced = it[it[\"inn\"].isin(years_present[years_present == it[\"year\"].nunique()].index)]\npanel = pd.DataFrame({\n    \"все компании\": it.groupby(\"year\")[\"ros\"].median(),\n    \"компаний\": it.groupby(\"year\")[\"inn\"].nunique(),\n    \"сбалансированная панель\": balanced.groupby(\"year\")[\"ros\"].median(),\n    \"компаний в панели\": balanced.groupby(\"year\")[\"inn\"].nunique(),\n})\npanel.round(3)\n#>       все компании  компаний  сбалансированная панель  компаний в панели\n#> year                                                                    \n#> 2018         0.043       660                    0.045                483\n#> 2019         0.046       715                    0.047                483\n#> 2020         0.049       795                    0.051                483\n#> 2021         0.066       870                    0.063                483\n#> 2022         0.064      1094                    0.062                483\n#> 2023         0.078      1153                    0.092                483\n#> 2024         0.074      1151                    0.080                483\n#> 2025         0.055      1124                    0.055                483\n```\n:::\n\n\n\n\nСостав выборки действительно менялся: в 2018 г. отчитались 660 ИТ-компаний, в 2023 г. – 1 153. Но в сбалансированной панели из 483 компаний медианная рентабельность выросла так же – с 4,5% до 9,2%. Значит, рост не сводится к смене состава: рентабельнее стали сами компании. И снижение в 2025 г. в панели тоже есть – до 5,5%: это изменение внутри компаний, а не результат того, что часть компаний перестала отчитываться. Если бы изменение было видно только по всем компаниям, а в панели – нет, объяснять его пришлось бы сменой состава. Обратите внимание, что сбалансированная панель тоже не свободна от смещения: в неё попадают только компании, которые проработали весь период, то есть «выжившие».\n\n## Структура балансов {#sec-profiles}\n\nОтрасли различаются не только рентабельностью, но и тем, во что вложены их активы. Посмотрим на медианные доли основных статей актива. Здесь пригодится особенность новых форм 2025 г. из предыдущей главы: компании, сдающие упрощённую отчётность, показывают дебиторскую задолженность в строке 1240, а не 1230. Если этого не учесть, у них дебиторка окажется пропущенной. В упрощённой форме строка 1240 включает и финансовые вложения, так что это приближение.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.python .cell-code}\nd23 = r[r[\"year\"] == YEAR]\n# с 2025 г. в упрощённой форме дебиторская задолженность – в строке 1240 (глава 5)\nreceivables = d23[\"line_1230\"].fillna(d23[\"line_1240\"].where(d23[\"simplified\"] == 1))\nprofile = pd.DataFrame({\n    \"осн. средства\": d23[\"line_1150\"] / d23[\"line_1600\"],\n    \"запасы\": d23[\"line_1210\"] / d23[\"line_1600\"],\n    \"дебиторка\": receivables / d23[\"line_1600\"],\n    \"деньги\": d23[\"line_1250\"] / d23[\"line_1600\"],\n}).groupby(d23[\"div\"]).median().rename(index=DIV)\nprofile.round(3)\n#>                       осн. средства  запасы  дебиторка  деньги\n#> div                                                           \n#> пищевые продукты              0.240   0.208      0.281   0.008\n#> строительство                 0.028   0.184      0.473   0.010\n#> розничная торговля            0.114   0.356      0.150   0.039\n#> сухопутный транспорт          0.387   0.024      0.331   0.006\n#> разработка ПО                 0.029   0.012      0.373   0.068\n```\n:::\n\n\n\n\nСтруктура баланса хорошо отражает бизнес-модель. У транспортных компаний основные средства – 39% активов: это подвижной состав, трубопроводы, терминалы. У розничных сетей самая большая статья – запасы (36%), то есть товары на полках и складах. У строителей и разработчиков программ основных средств почти нет, а крупнейшая статья активов – дебиторская задолженность (47% и 37%): неоплаченные заказчиками работы и авансы, выданные подрядчикам и поставщикам.\n\nТакой «профиль отрасли» полезен как ориентир: если структура баланса отдельной компании сильно отличается от типичной для её отрасли, стоит выяснить почему. Возможно, у компании особая бизнес-модель, а возможно, код ОКВЭД не отражает её реальную деятельность или в отчётности есть ошибки.\n\n## Итоги {.unnumbered}\n\n- Разложение DuPont делит рентабельность капитала на маржу, оборачиваемость активов и финансовый рычаг. Одинаковую ROE можно получить очень разными бизнес-моделями, а высокий рычаг означает не только доходность, но и риск. На данных у закредитованных компаний ROA ниже, а высокая ROE во многом механическая.\n- EBITDA по данным RFSD не считается: амортизации в отчётности нет. Используйте EBIT и прибыль от продаж под их настоящими названиями.\n- «Гипербола ROA» – карта бизнес-моделей: отрасли занимают на ней разные области, и сравнивать маржу компаний разных отраслей нельзя.\n- Концентрацию измеряют долей крупнейших компаний (CR5), индексом Херфиндаля – Хиршмана и коэффициентом Джини. Результат зависит от того, по какому кругу компаний он посчитан.\n- Сравнение лидеров и остальных – проверка гипотезы: нужны показатели, статистический критерий (для рентабельности – непараметрический) и осторожность в выводах о причинах.\n- Изменение медианы во времени может объясняться сменой состава компаний; проверка – сбалансированная панель.\n- Структура баланса отражает бизнес-модель отрасли и помогает находить нетипичные компании.\n\n## Упражнения {#sec-exercises-industry}\n\n### А. Понимание\n\n1. У компании рентабельность продаж 4%, оборачиваемость активов 2,5, мультипликатор капитала 3. Чему равны ROA и ROE? Как изменится ROE, если компания возьмёт кредит и мультипликатор вырастет до 5, а процентные расходы снизят маржу до 3%?\n2. На рынке пять компаний с долями 40%, 30%, 15%, 10% и 5%. Посчитайте CR3 и HHI. Как изменится HHI, если две крупнейшие компании объединятся?\n3. Почему для сравнения рентабельности двух групп компаний лучше использовать критерий Манна – Уитни, а не $t$-тест?\n4. В таблице раздела о рычаге медианная ROE растёт с долей обязательств, а медианная ROA падает. Приведите два объяснения и скажите, какие компании выпадают из расчёта ROE.\n\n### Б. Практика на своей отрасли\n\n5. Постройте для своей отрасли (полный RFSD, 2025 г.) гиперболу ROA. Найдите на графике компании с необычной бизнес-моделью и выясните, чем они занимаются.\n6. Посчитайте CR5, HHI и коэффициент Джини для своей отрасли за 2018 и 2025 гг. – по всем компаниям и только по компаниям с выручкой от 1 млрд руб. Объясните различия.\n7. Проверьте гипотезу «лидеры отрасли эффективнее остальных» для своей отрасли. За счёт какого множителя DuPont возникает разница?\n\n### В. Работа с ИИ-ассистентом\n\n8. Попросите ИИ-ассистента объяснить, почему ROE «Агроторга» выше, чем у «Тандера», при меньшей марже. Сравните его объяснение с разложением DuPont на данных. Упомянул ли ассистент, что речь идёт об отчётности отдельных юрлиц внутри групп?\n9. Попросите ассистента написать функцию расчёта HHI. Проверьте её на примере из упражнения 2. В каких единицах ассистент выражает доли и какой масштаб HHI получается?\n10. Попросите ассистента посчитать EBITDA-маржу вашей отрасли по данным RFSD. Какую строку он использует как амортизацию? Объясните, что на самом деле посчитано, и переделайте расчёт с честным названием показателя.\n\n### Г. Мини-исследование\n\n11. Выберите отрасль, пережившую крупное изменение регулирования или рынка (например, переход строительства на эскроу-счета в 2019 г. или уход иностранных компаний в 2022 г.), и проследите по RFSD, как изменились концентрация, рентабельность и структура балансов. Отделите изменения внутри компаний от изменения состава отрасли. Подготовьте короткий устный рассказ.\n12. Постройте гистограмму выручки всех компаний (полный RFSD) в диапазоне от 100 до 400 млн руб. за несколько лет. Есть ли скопление компаний чуть ниже порога доходов для упрощённой системы налогообложения (уточните порог для каждого года)? Как менялось положение скопления при изменении порога и что это говорит о поведении компаний?\n\n## Вопросы для самопроверки {.unnumbered}\n\n1. Запишите разложение DuPont. Какой множитель отвечает за финансовый риск?\n2. Что показывает гипербола ROA и почему её удобно строить в логарифмической шкале по оборачиваемости?\n3. Как считается индекс Херфиндаля – Хиршмана и в каких пределах он меняется?\n4. Почему рост медианной рентабельности отрасли не обязательно означает, что компании стали эффективнее?\n5. Какие статьи баланса преобладают у транспортных компаний, розничных сетей и строителей?\n\n::: {.callout-tip collapse=\"true\" title=\"Ответы\"}\n1. ROE = ROS × оборачиваемость × мультипликатор капитала; финансовый риск отражает мультипликатор (финансовый рычаг).\n2. Сочетания маржи и оборачиваемости с одинаковой ROA; логарифмическая шкала растягивает область низкой оборачиваемости, где лежит большинство капиталоёмких компаний.\n3. Сумма квадратов рыночных долей в процентах; от почти нуля (раздробленный рынок) до 10 000 (монополия).\n4. Из-за изменения состава компаний: могли прийти новые, более рентабельные, или уйти слабые. Проверка – сбалансированная панель.\n5. У транспорта – основные средства, у розницы – запасы, у строителей – дебиторская задолженность.\n:::\n\n## Что почитать {.unnumbered}\n\n- @bodie2021, глава об анализе финансовой отчётности – разложение DuPont и финансовые коэффициенты.\n- @bondarkov2025 – описание данных RFSD, в том числе примеры отраслевых распределений.\n",
    "supporting": [
      "06-industry-analysis_files\\figure-html"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}